/**
 * ThreatMatrix Report Generation Engine
 * Generates formatted Markdown, HTML, and JSON security compliance reports.
 */
import fs from 'fs';
import path from 'path';
import { logger } from './logger.js';

export interface ReportData {
  scanId: string;
  target?: string;
  threatLevel: string;
  riskScore: number;
  confidence: number;
  summary: string;
  findings: Array<{ category: string; description: string; severity: string }>;
  recommendations: string[];
  evidence?: any[];
  metadata?: Record<string, unknown>;
  details?: Record<string, unknown>;
}

export class ReportGenerator {
  private outputDirs = [
    path.resolve(process.cwd(), 'public/exports'),
    path.resolve(process.cwd(), 'generated/reports'),
  ];

  constructor() {
    this.outputDirs.forEach((dir) => {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    });
  }

  public generateJson(data: ReportData): { fileName: string; filePath: string; webPath: string; content: string } {
    const cleanScanId = (data.scanId || 'audit').replace(/[^a-zA-Z0-9_\-]/g, '_');
    const fileName = `report_${cleanScanId}.json`;
    const content = JSON.stringify({
      reportHeader: {
        system: 'ThreatMatrix Enterprise MCP Security Platform',
        version: '1.0.0',
        generatedAt: new Date().toISOString(),
      },
      ...data,
      scanId: cleanScanId,
    }, null, 2);

    const primaryPath = path.join(this.outputDirs[0], fileName);
    fs.writeFileSync(primaryPath, content, 'utf-8');

    return {
      fileName,
      filePath: primaryPath,
      webPath: `/exports/${fileName}`,
      content,
    };
  }

  public generateMarkdown(data: ReportData): { fileName: string; filePath: string; webPath: string; content: string } {
    const cleanScanId = (data.scanId || 'audit').replace(/[^a-zA-Z0-9_\-]/g, '_');
    const fileName = `report_${cleanScanId}.md`;
    const findingsMd = (data.findings || [])
      .map(f => `- **[${f.severity}]** \`${f.category}\`: ${f.description}`)
      .join('\n');

    const recsMd = (data.recommendations || [])
      .map(r => `- ${r}`)
      .join('\n');

    const content = `# 🛡️ ThreatMatrix Security Report

**Scan Audit ID:** \`${cleanScanId}\`  
**Generated At:** ${new Date().toISOString()}  
**Target:** \`${data.target || 'N/A'}\`  

---

## 📊 Risk Overview
- **Threat Level:** \`${data.threatLevel}\`
- **Risk Score:** \`${data.riskScore} / 100\`
- **Confidence Rating:** \`${Math.round(data.confidence * 100)}%\`

> ${data.summary}

---

## 🔍 Structural & Threat Findings
${findingsMd || 'No high-risk findings detected.'}

---

## 🛡️ Containment & Mitigation Playbook
${recsMd || 'Exercise standard security precautions.'}

---
*Report generated by ThreatMatrix Agentic AI Infrastructure.*
`;

    const primaryPath = path.join(this.outputDirs[0], fileName);
    fs.writeFileSync(primaryPath, content, 'utf-8');

    return {
      fileName,
      filePath: primaryPath,
      webPath: `/exports/${fileName}`,
      content,
    };
  }

  public generateHtml(data: ReportData): { fileName: string; filePath: string; webPath: string; content: string } {
    const cleanScanId = (data.scanId || 'audit').replace(/[^a-zA-Z0-9_\-]/g, '_');
    const fileName = `report_${cleanScanId}.html`;
    
    const findingsHtml = (data.findings || [])
      .map(f => `<li class="finding ${f.severity.toLowerCase()}"><strong>[${f.severity}]</strong> <code>${f.category}</code>: ${f.description}</li>`)
      .join('\n') || '<li>No high-risk findings detected.</li>';

    const recsHtml = (data.recommendations || [])
      .map(r => `<li>${r}</li>`)
      .join('\n') || '<li>Exercise standard security precautions.</li>';

    const content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ThreatMatrix Security Report — ${cleanScanId}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0b0d19; color: #e2e8f0; padding: 40px; line-height: 1.6; }
    .card { background: #13172e; border: 1px solid #2d3748; padding: 32px; border-radius: 16px; max-width: 800px; margin: 0 auto; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }
    h1 { color: #6366f1; border-bottom: 1px solid #2d3748; padding-bottom: 12px; }
    h2 { color: #a5b4fc; margin-top: 24px; }
    .badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-weight: bold; background: #ef4444; color: white; }
    .badge.SAFE { background: #10b981; }
    .badge.SUSPICIOUS { background: #f59e0b; }
    .badge.HIGH { background: #f97316; }
    code { background: #1e293b; padding: 2px 6px; border-radius: 4px; font-family: monospace; color: #a5b4fc; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
    li.finding.critical { color: #f87171; }
    li.finding.high { color: #fb923c; }
    li.finding.medium { color: #fbbf24; }
    li.finding.low { color: #34d399; }
  </style>
</head>
<body>
  <div class="card">
    <h1>🛡️ ThreatMatrix Executive Security Report</h1>
    <p><strong>Scan Audit ID:</strong> <code>${cleanScanId}</code> | <strong>Date:</strong> ${new Date().toISOString()}</p>
    <p><strong>Target:</strong> <code>${data.target || 'N/A'}</code></p>
    <div style="margin: 20px 0;">
      <span class="badge ${data.threatLevel}">${data.threatLevel} (${data.riskScore}/100)</span>
      <span style="margin-left: 12px; color: #94a3b8;">Confidence: ${Math.round(data.confidence * 100)}%</span>
    </div>
    <div style="background: #1e293b; padding: 16px; border-radius: 8px; margin-bottom: 24px;">
      <p style="margin: 0;">${data.summary}</p>
    </div>
    <h2>🔍 Structural & Threat Findings</h2>
    <ul>${findingsHtml}</ul>
    <h2>🛡️ Containment Playbook</h2>
    <ul>${recsHtml}</ul>
  </div>
</body>
</html>`;

    const primaryPath = path.join(this.outputDirs[0], fileName);
    fs.writeFileSync(primaryPath, content, 'utf-8');

    return {
      fileName,
      filePath: primaryPath,
      webPath: `/exports/${fileName}`,
      content,
    };
  }

  public generate(scanId: string, format: 'json' | 'markdown' | 'html' | 'pdf', data: ReportData) {
    logger.info('Generating security report', { scanId, format });
    switch (format) {
      case 'json': return this.generateJson(data);
      case 'html': return this.generateHtml(data);
      case 'markdown':
      case 'pdf':
      default:
        return this.generateMarkdown(data);
    }
  }
}
