import { z } from 'zod';

/**
 * Reroute / Contingency Plan Domain Types
 * Alternative logistics options generated by broker
 */

export enum RerouteStatus {
  PROPOSED = 'proposed',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  EXECUTED = 'executed',
  CANCELLED = 'cancelled',
}

export const RerouteOptionSchema = z.object({
  id: z.string().describe('Unique reroute option ID'),
  shipmentId: z.string().describe('Original shipment'),
  threatId: z.string().describe('Threat triggering reroute'),
  transportMode: z.enum(['sea', 'air', 'truck', 'rail', 'multimodal']).describe('New transport mode'),
  carrier: z.string().describe('Alternative carrier'),
  origin: z.object({
    port: z.string(),
    lat: z.number(),
    lng: z.number(),
  }).describe('Departure point'),
  destination: z.object({
    port: z.string(),
    lat: z.number(),
    lng: z.number(),
  }).describe('Arrival point'),
  estimatedDeparture: z.string().datetime().describe('Planned departure'),
  estimatedArrival: z.string().datetime().describe('Planned arrival'),
  delayReduction: z.number().describe('Hours saved vs. original route'),
  additionalCost: z.number().describe('Extra cost in USD'),
  costPerDay: z.number().describe('Cost per day of delay avoided'),
  riskScore: z.number().min(0).max(1).describe('Execution risk 0-1'),
  carrierReliability: z.number().min(0).max(1).describe('Carrier on-time rate'),
  capacity: z.number().describe('Available capacity in TEU or pallets'),
  spotRate: z.number().describe('Quoted rate in USD'),
  validUntil: z.string().datetime().describe('Quote expiration'),
  status: z.nativeEnum(RerouteStatus).describe('Approval status'),
  approvedBy: z.string().optional().describe('User who approved'),
  approvedAt: z.string().datetime().optional(),
  executedAt: z.string().datetime().optional(),
  bookingReference: z.string().optional().describe('Carrier booking ref'),
});

export type RerouteOption = z.infer<typeof RerouteOptionSchema>;

/**
 * Contingency Plan
 * Ranked set of reroute options for a shipment
 */
export const ContingencyPlanSchema = z.object({
  id: z.string().describe('Plan ID'),
  shipmentId: z.string().describe('Affected shipment'),
  threatId: z.string().describe('Triggering threat'),
  options: z.array(RerouteOptionSchema).describe('Ranked alternatives (best first)'),
  recommendation: z.object({
    optionId: z.string().describe('Recommended option ID'),
    rationale: z.string().describe('Why this option is best'),
    expectedOutcome: z.string().describe('Expected result if executed'),
  }).describe('Broker recommendation'),
  approvalRequired: z.boolean().describe('Needs human approval?'),
  approvalThreshold: z.number().optional().describe('Cost threshold for auto-approval'),
  createdAt: z.string().datetime(),
  expiresAt: z.string().datetime().describe('Plan validity window'),
});

export type ContingencyPlan = z.infer<typeof ContingencyPlanSchema>;

/**
 * Reroute Comparator Resource
 * Aggregated view of all active contingency plans
 */
export const RerouteComparatorSchema = z.object({
  id: z.string(),
  plans: z.array(ContingencyPlanSchema),
  totalAdditionalCost: z.number(),
  totalDelaySaved: z.number().describe('Total hours saved across all plans'),
  lastUpdated: z.string().datetime(),
});

export type RerouteComparator = z.infer<typeof RerouteComparatorSchema>;
