/**
 * EmailService
 * 
 * Wrapper around Resend SDK for sending Safe-T Claim dispute emails.
 * Adds [DEMO] prefix to subject line for hackathon safety.
 */

import { Injectable } from '@nitrostack/core';

@Injectable()
export class EmailService {
  /**
   * Send a Safe-T Claim dispute email via Resend.
   * In production, this would use the actual Resend SDK.
   * For now, we simulate the send and log it.
   */
  async sendSafeTClaim(input: {
    orderId: string;
    claimValueINR: number;
    fraudScore: number;
    recipientEmail: string;
  }): Promise<{ messageId: string; status: string }> {
    // In a real implementation, this would call:
    // const { data, error } = await resend.emails.send({...})

    // For demo purposes, simulate a successful send
    const messageId = `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // Log the email (in production, this would be sent via Resend)
    console.log('[DEMO] Safe-T Claim Email Sent:', {
      messageId,
      to: input.recipientEmail,
      subject: `[DEMO] Safe-T Claim Dispute - Order ${input.orderId}`,
      claimValueINR: input.claimValueINR,
      fraudScore: input.fraudScore,
      timestamp: new Date().toISOString(),
    });

    return {
      messageId,
      status: 'sent',
    };
  }

  /**
   * Generate the HTML email body for a Safe-T Claim
   */
  private generateEmailBody(input: {
    orderId: string;
    claimValueINR: number;
    fraudScore: number;
  }): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .alert { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin-bottom: 20px; }
    .details { background: #f8f9fa; padding: 16px; border-radius: 8px; margin-bottom: 20px; }
    .footer { font-size: 12px; color: #666; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>[DEMO] Safe-T Claim Dispute Notice</h2>
      <p><strong>This is a simulated claim for hackathon demonstration purposes.</strong></p>
    </div>

    <div class="alert">
      <strong>⚠️ Important:</strong> This email is part of a hackathon demo. No actual claim has been filed.
    </div>

    <div class="details">
      <h3>Claim Details</h3>
      <p><strong>Order ID:</strong> ${input.orderId}</p>
      <p><strong>Claim Value:</strong> ₹${input.claimValueINR.toLocaleString('en-IN')}</p>
      <p><strong>Fraud Confidence Score:</strong> ${input.fraudScore}%</p>
    </div>

    <div class="footer">
      <p>This email was generated by SentryFlow, an MCP-based fraud detection system.</p>
      <p>Sent at: ${new Date().toISOString()}</p>
    </div>
  </div>
</body>
</html>
    `;
  }
}
