import { ToolDecorator as Tool, ControllerDecorator as Controller, Widget, z, ExecutionContext, Injectable } from '@nitrostack/core';
import { AuthService } from '../services/auth.service.js';

@Injectable({ deps: [AuthService] })
@Controller()
export class RemediationTools {
    constructor(private authService: AuthService) {}

    @Widget({ route: 'approval-dashboard' })
    @Tool({
        name: 'execute_rollback',
        description: 'Executes a rollback or patch to fix a broken service. Requires a unique incident_id and human approval via chat (action: "approve").',
        inputSchema: z.object({
            service_name: z.string().min(3).regex(/^[a-zA-Z0-9_-]+$/, 'Service name must only contain alphanumeric characters, dashes, and underscores'),
            incident_id: z.string().min(3).describe('The unique incident ID generated by the workflow prompt (e.g. INC-A1B2C3D4)'),
            commit_hash: z.string().optional().describe('The git commit hash to rollback from'),
            reason: z.string().min(10, 'Reason must be at least 10 characters').describe('Explanation of why this rollback is necessary'),
            action: z.enum(['pending', 'approve', 'deny']).optional().describe('Set to "approve" to execute the rollback directly from chat.')
        })
    })
    async executeRollback(
        input: { service_name: string; incident_id: string; commit_hash?: string; reason: string; action?: 'pending' | 'approve' | 'deny' },
        ctx: ExecutionContext
    ) {
        ctx.logger.warn(`[${input.incident_id}] Rollback requested for ${input.service_name}. Reason: ${input.reason}`);

        const schema = z.object({
            service_name: z.string().min(3).regex(/^[a-zA-Z0-9_-]+$/, 'Service name must only contain alphanumeric characters, dashes, and underscores'),
            incident_id: z.string().min(3),
            commit_hash: z.string().optional(),
            reason: z.string().min(10),
            action: z.enum(['pending', 'approve', 'deny']).optional()
        });
        const parseResult = schema.safeParse(input);
        if (!parseResult.success) {
            return {
                success: false,
                error: `Validation failed: ${parseResult.error.errors.map(e => e.message).join(', ')}`
            };
        }

        this.authService.addAuditEntry({
            event: `execute_rollback REQUESTED [${input.incident_id}]`,
            actor: 'AI Agent',
            service: input.service_name,
            result: 'success',
        });

        try {
            // Step 1: If no action yet, create a pending approval request
            if (!input.action || input.action === 'pending') {
                this.authService.setPendingIncident(input.incident_id, {
                    service_name: input.service_name,
                    reason: input.reason,
                    commit_hash: input.commit_hash,
                });
                return {
                    status: 'PENDING_APPROVAL',
                    incident_id: input.incident_id,
                    service_name: input.service_name,
                    commit_hash: input.commit_hash,
                    reason: input.reason,
                    message: `Zero-Trust gate activated for incident ${input.incident_id}. Please confirm with the human operator and run execute_rollback again with action="approve" to proceed.`,
                    widget_uri: 'ui://approval-dashboard'
                };
            }

            // Step 2: Explicit deny
            if (input.action === 'deny') {
                this.authService.addAuditEntry({ event: `execute_rollback DENIED [${input.incident_id}]`, actor: 'Operator', service: input.service_name, result: 'denied' });
                return { success: false, status: 'DENIED', incident_id: input.incident_id, message: 'Rollback aborted by human operator.' };
            }

            // Step 3: Direct approval — no JWT needed
            // User typed "approve" in chat, so we trust the MCP context

            this.authService.addAuditEntry({ event: `execute_rollback EXECUTED [${input.incident_id}]`, actor: 'AI Agent (authorized)', service: input.service_name, result: 'success' });
            return {
                success: true,
                status: 'SUCCESS',
                incident_id: input.incident_id,
                authorized_by: 'Chat Approval',
                message: `✓ Service "${input.service_name}" successfully patched and restarted.`,
                action_taken: input.reason,
                rolled_back_at: new Date().toISOString(),
            };

        } catch (error: any) {
            ctx.logger.error(`[${input.incident_id}] Error in executeRollback: ${error.message}`);
            return { success: false, error: `Internal tool error: ${error.message}` };
        }
    }
}
