/**
 * Turns a plan_remediation plan into an actual edit: mutates a parsed
 * package.json object in place (preserving each dependency's original
 * range-operator prefix — "^4.17.15" becomes "^4.18.0", not a bare
 * "4.18.0"), and builds the PR description that explains what changed
 * and, just as importantly, what didn't.
 */

export interface PlanEntry {
  package: string;
  current_version: string;
  target_version: string;
  ecosystem?: "npm" | "PyPI" | "Go";
  breaking?: boolean;
  fixes?: string[];
  unresolved?: string[];
  escalations?: number;
  escalation_notes?: string[];
}

export interface AppliedChange {
  package: string;
  from: string;
  to: string;
}

export interface SkippedChange {
  package: string;
  reason: string;
}

const DEPENDENCY_SECTIONS = ["dependencies", "devDependencies"] as const;

export function applyPlanToManifestJson(
  json: Record<string, unknown>,
  plan: PlanEntry[]
): { applied: AppliedChange[]; skipped: SkippedChange[] } {
  const applied: AppliedChange[] = [];
  const skipped: SkippedChange[] = [];

  const toApply = plan.filter((p) => (p.fixes?.length ?? 0) > 0 && p.target_version !== p.current_version);

  for (const entry of toApply) {
    let touched = false;
    for (const section of DEPENDENCY_SECTIONS) {
      const block = json[section];
      if (!block || typeof block !== "object" || !(entry.package in (block as Record<string, unknown>))) continue;
      const originalRange = String((block as Record<string, unknown>)[entry.package]);
      const prefix = originalRange.match(/^[\^~>=<]*/)?.[0] ?? "";
      (block as Record<string, unknown>)[entry.package] = `${prefix}${entry.target_version}`;
      touched = true;
    }
    if (touched) {
      applied.push({ package: entry.package, from: entry.current_version, to: entry.target_version });
    } else {
      skipped.push({ package: entry.package, reason: "Not found in dependencies/devDependencies of the provided manifest." });
    }
  }

  return { applied, skipped };
}

export function buildPrBody(applied: AppliedChange[], breaking: AppliedChange[], unresolved: string[]): string {
  const lines: string[] = [];
  lines.push("## Dependency security patch");
  lines.push("");
  lines.push(
    applied.length > 0
      ? `Upgrades ${applied.length} package${applied.length === 1 ? "" : "s"} to clear known vulnerabilities, ranked by real-world exploitation evidence (CISA KEV + FIRST EPSS), not raw CVSS.`
      : "No packages needed an upgrade."
  );

  if (applied.length > 0) {
    lines.push("");
    lines.push("### Upgraded");
    for (const a of applied) lines.push(`- \`${a.package}\`: ${a.from} → ${a.to}`);
  }

  lines.push("");
  lines.push("### ⚠️ Breaking changes");
  if (breaking.length > 0) {
    for (const b of breaking) lines.push(`- \`${b.package}\`: ${b.from} → ${b.to} is a **major version bump**. Review the changelog before merging.`);
  } else {
    lines.push("None — every upgrade here stays within its current major version.");
  }

  lines.push("");
  lines.push("### Not fixed by this patch");
  if (unresolved.length > 0) {
    lines.push("These have no known fix in OSV.dev yet — upgrading will not resolve them:");
    for (const u of unresolved) lines.push(`- ${u}`);
  } else {
    lines.push("None — every identified vulnerability has a fix applied above.");
  }

  lines.push("");
  lines.push("_Generated by WARDEN. Run verify_fix after applying to confirm against OSV.dev's live database._");
  return lines.join("\n");
}
