import React, { useState } from 'react';
import type { WorkOrder } from '../types';
import { Layers, UserCheck, AlertOctagon, DollarSign, Package, Wrench, AlertTriangle } from 'lucide-react';

interface WorkOrdersProps {
  workOrders: WorkOrder[];
  activeWorkOrder?: WorkOrder;
  onUpdateStatus: (workOrderId: string, status: WorkOrder['status']) => void;
}

export const WorkOrders: React.FC<WorkOrdersProps> = ({
  workOrders,
  activeWorkOrder,
  onUpdateStatus,
}) => {
  const [selectedWorkOrder, setSelectedWorkOrder] = useState<WorkOrder>(activeWorkOrder || workOrders[0]);
  const [simulatedDowntime, setSimulatedDowntime] = useState<number>(
    selectedWorkOrder?.estimatedImpact.downtimeMinutes || 45
  );

  // Static formula calculation: units/hr * (downtime_min / 60) * $140 per unit
  const unitsPerHour = 120;
  const unitRevenueUsd = 140;
  const calculatedUnitsLost = Math.round(unitsPerHour * (simulatedDowntime / 60));
  const calculatedFinancialImpact = calculatedUnitsLost * unitRevenueUsd;

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 420px', gap: '1.25rem', padding: '1.25rem' }}>
      
      {/* Left Column: Active Work Orders Table & Dispatch Cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        
        <div className="glass-panel" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div>
              <h2 style={{ fontSize: '1.15rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Layers size={18} color="var(--primary)" />
                Work Order Management Center
              </h2>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                Auto-generated by NitroStack MCP tool `create_work_order`
              </p>
            </div>

            <span className="code-font" style={{ fontSize: '0.78rem', background: 'rgba(255,255,255,0.05)', padding: '0.3rem 0.7rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
              Total Orders: {workOrders.length}
            </span>
          </div>

          {/* Work Orders List / Grid */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
            {workOrders.map((wo) => {
              const isSelected = selectedWorkOrder.id === wo.id;
              const hasStockout = wo.requiredParts.some((p) => !p.isAvailable);

              return (
                <div
                  key={wo.id}
                  onClick={() => {
                    setSelectedWorkOrder(wo);
                    setSimulatedDowntime(wo.estimatedImpact.downtimeMinutes);
                  }}
                  className={`glass-panel ${hasStockout ? 'glass-panel-critical' : isSelected ? 'glass-panel-glow' : ''}`}
                  style={{
                    padding: '1rem',
                    cursor: 'pointer',
                    background: isSelected ? 'rgba(0, 242, 255, 0.05)' : undefined,
                    transition: 'all 0.2s ease'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                      <span className="code-font" style={{ fontWeight: 800, color: 'var(--primary)', fontSize: '0.9rem' }}>
                        {wo.id}
                      </span>
                      <span className={`status-pill ${wo.severity === 'CRITICAL' ? 'critical' : 'warning'}`}>
                        {wo.severity} SEVERITY
                      </span>
                      {hasStockout && (
                        <span className="status-pill critical" style={{ fontSize: '0.68rem' }}>
                          <AlertTriangle size={11} /> STOCKOUT ALERT
                        </span>
                      )}
                    </div>

                    <span className="code-font" style={{ fontSize: '0.7rem', color: 'var(--text-dim)' }}>
                      {wo.createdAt}
                    </span>
                  </div>

                  <h3 style={{ fontSize: '0.95rem', marginBottom: '0.3rem', color: 'var(--text-main)' }}>
                    {wo.issueSummary}
                  </h3>

                  <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginBottom: '0.6rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    <Wrench size={13} color="var(--primary)" /> Target: <strong>{wo.machineName}</strong> ({wo.machineId}) — {wo.line}
                  </p>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border-color)', paddingTop: '0.5rem', fontSize: '0.75rem' }}>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', color: 'var(--text-muted)' }}>
                      <UserCheck size={13} color="var(--emerald)" /> Assigned: <strong style={{ color: 'var(--text-main)' }}>{wo.assignedTechnician.name}</strong>
                    </span>

                    <span className="code-font" style={{ color: 'var(--emerald)', fontWeight: 700 }}>
                      Est. Impact: ${wo.estimatedImpact.financialImpactUsd.toLocaleString()}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>

      {/* Right Column: Work Order Inspector, Spare Parts Stock & Production Impact Calculator */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        
        {/* Selected Work Order Inspector */}
        <div className="glass-panel glass-panel-glow" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
            <span className="code-font" style={{ fontSize: '0.75rem', color: 'var(--primary)', fontWeight: 800 }}>
              WORK ORDER DETAILS ({selectedWorkOrder.id})
            </span>
            <span className="status-pill healthy">
              {selectedWorkOrder.status}
            </span>
          </div>

          <h3 style={{ fontSize: '1.05rem', fontWeight: 800, marginBottom: '0.4rem' }}>
            {selectedWorkOrder.issueSummary}
          </h3>

          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1rem', lineHeight: '1.4' }}>
            <strong>Diagnosed Root Cause:</strong> {selectedWorkOrder.rootCause}
          </p>

          {/* Assigned Technician Box */}
          <div style={{ background: 'rgba(0, 255, 157, 0.05)', border: '1px solid rgba(0, 255, 157, 0.2)', padding: '0.8rem', borderRadius: '8px', marginBottom: '1rem' }}>
            <span style={{ fontSize: '0.7rem', color: 'var(--emerald)', fontWeight: 700, textTransform: 'uppercase', display: 'block', marginBottom: '0.2rem' }}>
              Assigned Field Technician:
            </span>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <strong style={{ fontSize: '0.9rem', color: 'var(--text-main)' }}>{selectedWorkOrder.assignedTechnician.name}</strong>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{selectedWorkOrder.assignedTechnician.specialty}</div>
              </div>
              <span className="code-font" style={{ fontSize: '0.68rem', background: 'rgba(0, 255, 157, 0.15)', color: 'var(--emerald)', padding: '0.2rem 0.5rem', borderRadius: '4px' }}>
                {selectedWorkOrder.assignedTechnician.availability}
              </span>
            </div>
          </div>

          {/* Required Spare Parts Verification */}
          <div style={{ marginBottom: '1rem' }}>
            <h4 style={{ fontSize: '0.85rem', color: 'var(--text-main)', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <Package size={15} color="var(--primary)" /> Required Spare Parts Stock Check:
            </h4>

            {selectedWorkOrder.requiredParts.map((part) => (
              <div
                key={part.partId}
                style={{
                  background: part.isAvailable ? 'rgba(255,255,255,0.03)' : 'rgba(255, 51, 102, 0.1)',
                  border: `1px solid ${part.isAvailable ? 'var(--border-color)' : 'rgba(255, 51, 102, 0.4)'}`,
                  padding: '0.6rem 0.8rem',
                  borderRadius: '6px',
                  marginBottom: '0.4rem',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  fontSize: '0.78rem'
                }}
              >
                <div>
                  <div className="code-font" style={{ fontWeight: 700, color: part.isAvailable ? 'var(--text-main)' : 'var(--crimson)' }}>
                    {part.partName} ({part.partId})
                  </div>
                  <div style={{ fontSize: '0.7rem', color: 'var(--text-dim)' }}>Required: {part.requiredQty} unit(s)</div>
                </div>

                <div style={{ textAlign: 'right' }}>
                  {part.isAvailable ? (
                    <span className="code-font" style={{ color: 'var(--emerald)', fontWeight: 700 }}>
                      IN STOCK ({part.inStockQty})
                    </span>
                  ) : (
                    <span className="code-font" style={{ color: 'var(--crimson)', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '0.2rem' }}>
                      <AlertOctagon size={12} /> STOCKOUT (0 Available)
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Status Workflow Action Buttons */}
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button
              onClick={() => onUpdateStatus(selectedWorkOrder.id, 'IN_PROGRESS')}
              className="btn-primary"
              style={{ flex: 1, justifyContent: 'center', fontSize: '0.78rem' }}
            >
              Start Maintenance Work
            </button>

            <button
              onClick={() => onUpdateStatus(selectedWorkOrder.id, 'COMPLETED')}
              className="btn-outline"
              style={{ flex: 1, justifyContent: 'center', fontSize: '0.78rem', borderColor: 'var(--emerald)', color: 'var(--emerald)' }}
            >
              Mark Completed
            </button>
          </div>
        </div>

        {/* Production Impact Estimator Widget (NitroStack MCP estimate_production_impact tool) */}
        <div className="glass-panel" style={{ padding: '1.25rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
            <h3 style={{ fontSize: '0.95rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <DollarSign size={16} color="var(--emerald)" />
              Production Impact Estimator
            </h3>
            <span className="badge-nitro" style={{ fontSize: '0.65rem' }}>
              Formula: units/hr × downtime
            </span>
          </div>

          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
            Calculates financial loss and volume impact based on machine line throughput (120 units/hr @ $140/unit).
          </p>

          {/* Downtime Slider */}
          <div style={{ marginBottom: '1.25rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '0.4rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>Simulated Downtime Duration:</span>
              <strong className="code-font" style={{ color: 'var(--primary)', fontSize: '0.9rem' }}>
                {simulatedDowntime} minutes
              </strong>
            </div>

            <input
              type="range"
              min="10"
              max="240"
              step="5"
              value={simulatedDowntime}
              onChange={(e) => setSimulatedDowntime(Number(e.target.value))}
              style={{ width: '100%', accentColor: 'var(--primary)' }}
            />
          </div>

          {/* Calculated Impact Metrics Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>
            <div className="metric-tile">
              <span style={{ fontSize: '0.7rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.2rem' }}>
                Estimated Lost Production Volume:
              </span>
              <div className="metric-value" style={{ color: 'var(--amber)' }}>
                {calculatedUnitsLost.toLocaleString()} <span style={{ fontSize: '0.8rem' }}>units</span>
              </div>
            </div>

            <div className="metric-tile">
              <span style={{ fontSize: '0.7rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.2rem' }}>
                Total Revenue Impact ($):
              </span>
              <div className="metric-value" style={{ color: 'var(--crimson)' }}>
                ${calculatedFinancialImpact.toLocaleString()}
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  );
};
