/**
 * EV Battery Material Advisor — Seed Data
 *
 * Representative materials database covering cathode, anode, electrolyte,
 * separator, current-collector, and casing component types.
 * All metrics are based on published literature ranges (2023-2025).
 */

import type { RankedMaterial } from '../../schemas/material-metrics.schema.js';

export const CANDIDATE_MATERIALS: Omit<RankedMaterial, 'compositeScore' | 'rank'>[] = [
    // ── Cathodes ──────────────────────────────────────────────────────────────
    {
        id: 'nmc811-cathode',
        name: 'NMC 811',
        chemistryFamily: 'NMC',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 280,
            volumetricEnergyDensity: 700,
            specificCapacity: 200,
            ionicConductivity: 1e-3,
            coulombicEfficiency: 99.0,
            cycleLifeTo80SOH: 1000,
            calendarLifeSelfDischarge: 0.5,
            cRateCapability: 3.0,
            thermalRunawayOnsetTemp: 170,
            operatingTempRange: { min: -20, max: 55 },
            volumeExpansion: 4,
            structuralStrengthToWeight: 450,
            materialCostPerKWh: 85,
            carbonFootprint: 65,
            recyclability: 70,
            criticalMineralDependency: 8.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['Highest energy density in commercial cathodes', 'Good power capability'],
        weaknesses: ['High cobalt/nickel dependency', 'Thermal stability concerns at high SOC', 'Higher cost'],
        dataConfidence: 0.92,
    },
    {
        id: 'nmc622-cathode',
        name: 'NMC 622',
        chemistryFamily: 'NMC',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 260,
            volumetricEnergyDensity: 650,
            specificCapacity: 175,
            ionicConductivity: 9e-4,
            coulombicEfficiency: 99.2,
            cycleLifeTo80SOH: 1500,
            calendarLifeSelfDischarge: 0.4,
            cRateCapability: 2.5,
            thermalRunawayOnsetTemp: 185,
            operatingTempRange: { min: -25, max: 55 },
            volumeExpansion: 3.5,
            structuralStrengthToWeight: 460,
            materialCostPerKWh: 75,
            carbonFootprint: 55,
            recyclability: 72,
            criticalMineralDependency: 7.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['Balanced energy/cycle life', 'Better thermal stability than NMC 811', 'Moderate cost'],
        weaknesses: ['Lower energy density than NMC 811', 'Still cobalt-dependent'],
        dataConfidence: 0.93,
    },
    {
        id: 'lfp-cathode',
        name: 'LFP (LiFePO₄)',
        chemistryFamily: 'LFP',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 160,
            volumetricEnergyDensity: 380,
            specificCapacity: 160,
            ionicConductivity: 1e-4,
            coulombicEfficiency: 99.8,
            cycleLifeTo80SOH: 3500,
            calendarLifeSelfDischarge: 0.25,
            cRateCapability: 2.0,
            thermalRunawayOnsetTemp: 270,
            operatingTempRange: { min: -30, max: 60 },
            volumeExpansion: 2,
            structuralStrengthToWeight: 500,
            materialCostPerKWh: 50,
            carbonFootprint: 35,
            recyclability: 85,
            criticalMineralDependency: 2.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Excellent cycle life (3500+ cycles)', 'Outstanding thermal safety', 'Low cost', 'No cobalt'],
        weaknesses: ['Lower energy density limits range', 'Reduced low-temperature performance'],
        dataConfidence: 0.97,
    },
    {
        id: 'lmfp-cathode',
        name: 'LMFP (LiMnFePO₄)',
        chemistryFamily: 'LMFP',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 185,
            volumetricEnergyDensity: 420,
            specificCapacity: 155,
            ionicConductivity: 1.2e-4,
            coulombicEfficiency: 99.5,
            cycleLifeTo80SOH: 2500,
            calendarLifeSelfDischarge: 0.3,
            cRateCapability: 2.2,
            thermalRunawayOnsetTemp: 255,
            operatingTempRange: { min: -25, max: 60 },
            volumeExpansion: 2.5,
            structuralStrengthToWeight: 490,
            materialCostPerKWh: 58,
            carbonFootprint: 38,
            recyclability: 82,
            criticalMineralDependency: 2.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Higher energy density than LFP', 'Excellent safety profile', 'Good cycle life', 'Low critical minerals'],
        weaknesses: ['Manganese dissolution at elevated temps', 'Slightly lower cycle life vs LFP'],
        dataConfidence: 0.82,
    },
    {
        id: 'nca-cathode',
        name: 'NCA (LiNiCoAlO₂)',
        chemistryFamily: 'NCA',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 270,
            volumetricEnergyDensity: 680,
            specificCapacity: 190,
            ionicConductivity: 1.1e-3,
            coulombicEfficiency: 99.1,
            cycleLifeTo80SOH: 1200,
            calendarLifeSelfDischarge: 0.45,
            cRateCapability: 3.5,
            thermalRunawayOnsetTemp: 165,
            operatingTempRange: { min: -20, max: 55 },
            volumeExpansion: 4,
            structuralStrengthToWeight: 445,
            materialCostPerKWh: 90,
            carbonFootprint: 70,
            recyclability: 68,
            criticalMineralDependency: 8.0,
            regulatoryCompliance: { un383: true, reach: false, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['High energy density', 'Excellent C-rate capability', 'Good cycle life'],
        weaknesses: ['Highest critical mineral dependency', 'Thermal stability concerns', 'REACH compliance gap'],
        dataConfidence: 0.91,
    },
    {
        id: 'lnmo-cathode',
        name: 'LNMO (High-Voltage Spinel)',
        chemistryFamily: 'LNMO',
        componentType: 'cathode',
        metrics: {
            gravimetricEnergyDensity: 200,
            volumetricEnergyDensity: 480,
            specificCapacity: 145,
            ionicConductivity: 1e-5,
            coulombicEfficiency: 98.5,
            cycleLifeTo80SOH: 1500,
            calendarLifeSelfDischarge: 0.6,
            cRateCapability: 5.0,
            thermalRunawayOnsetTemp: 240,
            operatingTempRange: { min: -20, max: 60 },
            volumeExpansion: 1,
            structuralStrengthToWeight: 510,
            materialCostPerKWh: 40,
            carbonFootprint: 30,
            recyclability: 80,
            criticalMineralDependency: 1.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['High operating voltage (4.7V)', 'Low cost, zero cobalt', 'Excellent fast charge'],
        weaknesses: ['Severe electrolyte oxidation at high voltage', 'Requires specialized electrolytes'],
        dataConfidence: 0.85,
    },

    // ── Anodes ────────────────────────────────────────────────────────────────
    {
        id: 'graphite-anode',
        name: 'Graphite (Natural/Synthetic)',
        chemistryFamily: 'Graphite',
        componentType: 'anode',
        metrics: {
            gravimetricEnergyDensity: 372,
            volumetricEnergyDensity: 620,
            specificCapacity: 372,
            ionicConductivity: 1e-2,
            coulombicEfficiency: 99.5,
            cycleLifeTo80SOH: 1000,
            calendarLifeSelfDischarge: 0.1,
            cRateCapability: 2.0,
            thermalRunawayOnsetTemp: 750,
            operatingTempRange: { min: -30, max: 60 },
            volumeExpansion: 12,
            structuralStrengthToWeight: 600,
            materialCostPerKWh: 8,
            carbonFootprint: 12,
            recyclability: 78,
            criticalMineralDependency: 3.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Most mature anode technology', 'Excellent cycle life', 'Low cost', 'Well-understood degradation'],
        weaknesses: ['Limited C-rate capability limits ultra-fast charging', 'Lithium plating risk at low temperatures'],
        dataConfidence: 0.98,
    },
    {
        id: 'silicon-graphite-anode',
        name: 'Silicon-Graphite Composite (10% Si)',
        chemistryFamily: 'Silicon-Composite',
        componentType: 'anode',
        metrics: {
            gravimetricEnergyDensity: 500,
            volumetricEnergyDensity: 780,
            specificCapacity: 500,
            ionicConductivity: 8e-3,
            coulombicEfficiency: 98.5,
            cycleLifeTo80SOH: 700,
            calendarLifeSelfDischarge: 0.15,
            cRateCapability: 2.5,
            thermalRunawayOnsetTemp: 700,
            operatingTempRange: { min: -25, max: 55 },
            volumeExpansion: 45,
            structuralStrengthToWeight: 520,
            materialCostPerKWh: 18,
            carbonFootprint: 20,
            recyclability: 65,
            criticalMineralDependency: 4.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['30% higher capacity than pure graphite', 'Better energy density', 'Improved fast-charge'],
        weaknesses: ['High volume expansion (45%) stresses cell structure', 'Reduced cycle life vs graphite', 'SEI instability'],
        dataConfidence: 0.85,
    },
    {
        id: 'silicon-anode',
        name: 'Pure Silicon Anode',
        chemistryFamily: 'Silicon',
        componentType: 'anode',
        metrics: {
            gravimetricEnergyDensity: 4200,
            volumetricEnergyDensity: 2190,
            specificCapacity: 4200,
            ionicConductivity: 1e-3,
            coulombicEfficiency: 95.0,
            cycleLifeTo80SOH: 200,
            calendarLifeSelfDischarge: 0.4,
            cRateCapability: 1.5,
            thermalRunawayOnsetTemp: 650,
            operatingTempRange: { min: -20, max: 50 },
            volumeExpansion: 300,
            structuralStrengthToWeight: 380,
            materialCostPerKWh: 45,
            carbonFootprint: 30,
            recyclability: 55,
            criticalMineralDependency: 3.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['Highest theoretical capacity (4200 mAh/g)', 'Exceptional energy density potential'],
        weaknesses: ['~300% volume expansion causes rapid failure', 'Very low cycle life in current form', 'Research-stage only'],
        dataConfidence: 0.70,
    },
    {
        id: 'lto-anode',
        name: 'LTO (Lithium Titanate)',
        chemistryFamily: 'LTO',
        componentType: 'anode',
        metrics: {
            gravimetricEnergyDensity: 175,
            volumetricEnergyDensity: 300,
            specificCapacity: 175,
            ionicConductivity: 1e-4,
            coulombicEfficiency: 99.9,
            cycleLifeTo80SOH: 15000,
            calendarLifeSelfDischarge: 0.05,
            cRateCapability: 10.0,
            thermalRunawayOnsetTemp: 900,
            operatingTempRange: { min: -40, max: 65 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 650,
            materialCostPerKWh: 35,
            carbonFootprint: 15,
            recyclability: 70,
            criticalMineralDependency: 1.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Incredible cycle life (15000+)', 'Extreme fast charging (10C+)', 'No lithium plating at low temps', 'Zero volume expansion'],
        weaknesses: ['Very low energy density', 'High cost per kWh compared to graphite'],
        dataConfidence: 0.96,
    },
    {
        id: 'lithium-metal-anode',
        name: 'Lithium Metal Anode',
        chemistryFamily: 'Lithium-Metal',
        componentType: 'anode',
        metrics: {
            gravimetricEnergyDensity: 3860,
            volumetricEnergyDensity: 2061,
            specificCapacity: 3860,
            ionicConductivity: 1e-1,
            coulombicEfficiency: 90.0,
            cycleLifeTo80SOH: 300,
            calendarLifeSelfDischarge: 1.0,
            cRateCapability: 1.0,
            thermalRunawayOnsetTemp: 180,
            operatingTempRange: { min: 0, max: 40 },
            volumeExpansion: 100,
            structuralStrengthToWeight: 200,
            materialCostPerKWh: 70,
            carbonFootprint: 40,
            recyclability: 50,
            criticalMineralDependency: 9.0,
            regulatoryCompliance: { un383: false, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['Highest possible energy density', 'Holy grail of anodes'],
        weaknesses: ['Dendrite formation causes short circuits', 'Extremely reactive, difficult to manufacture safely', 'Poor cycle life currently'],
        dataConfidence: 0.75,
    },

    // ── Electrolytes ──────────────────────────────────────────────────────────
    {
        id: 'lpe-liquid-electrolyte',
        name: 'Liquid Carbonate Electrolyte (LP30/LP40)',
        chemistryFamily: 'Liquid-Carbonate',
        componentType: 'electrolyte',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 1e-2,
            coulombicEfficiency: 99.8,
            cycleLifeTo80SOH: 1000,
            calendarLifeSelfDischarge: 0.2,
            cRateCapability: 5.0,
            thermalRunawayOnsetTemp: 60,
            operatingTempRange: { min: -30, max: 60 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 0,
            materialCostPerKWh: 5,
            carbonFootprint: 8,
            recyclability: 40,
            criticalMineralDependency: 2.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: false },
        },
        strengths: ['Highest ionic conductivity of any electrolyte', 'Low cost', 'Mature technology'],
        weaknesses: ['Flammable — thermal runaway onset at ~60°C', 'Leakage risk', 'Poor recyclability'],
        dataConfidence: 0.97,
    },
    {
        id: 'solid-oxide-electrolyte',
        name: 'Solid Oxide Electrolyte (LLZO)',
        chemistryFamily: 'Solid-State',
        componentType: 'electrolyte',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 1e-3,
            coulombicEfficiency: 99.9,
            cycleLifeTo80SOH: 3000,
            calendarLifeSelfDischarge: 0.05,
            cRateCapability: 2.0,
            thermalRunawayOnsetTemp: 900,
            operatingTempRange: { min: -40, max: 80 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 800,
            materialCostPerKWh: 120,
            carbonFootprint: 50,
            recyclability: 60,
            criticalMineralDependency: 4.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Non-flammable — inherently safe', 'Enables lithium metal anode', 'Extreme temperature range'],
        weaknesses: ['High manufacturing cost', 'Brittle — interface contact resistance issues', 'Lower ionic conductivity vs liquid'],
        dataConfidence: 0.68,
    },
    {
        id: 'peo-polymer-electrolyte',
        name: 'PEO Solid Polymer Electrolyte',
        chemistryFamily: 'Solid-Polymer',
        componentType: 'electrolyte',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 5e-4,
            coulombicEfficiency: 99.5,
            cycleLifeTo80SOH: 1500,
            calendarLifeSelfDischarge: 0.1,
            cRateCapability: 1.0,
            thermalRunawayOnsetTemp: 400,
            operatingTempRange: { min: 40, max: 80 },
            volumeExpansion: 2,
            structuralStrengthToWeight: 200,
            materialCostPerKWh: 15,
            carbonFootprint: 10,
            recyclability: 50,
            criticalMineralDependency: 1.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Flexible, easy to manufacture', 'Safer than liquid electrolytes'],
        weaknesses: ['Requires heating (40°C+) to achieve usable ionic conductivity', 'Poor oxidation stability at high voltages'],
        dataConfidence: 0.90,
    },

    // ── Separators ────────────────────────────────────────────────────────────
    {
        id: 'pe-separator',
        name: 'Polyethylene Separator (PE)',
        chemistryFamily: 'Polyolefin',
        componentType: 'separator',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 0,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 2000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 5.0,
            thermalRunawayOnsetTemp: 130,
            operatingTempRange: { min: -40, max: 90 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 700,
            materialCostPerKWh: 3,
            carbonFootprint: 5,
            recyclability: 50,
            criticalMineralDependency: 0.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Industry standard — lowest cost', 'Excellent ionic permeability', 'Mature supply chain'],
        weaknesses: ['Low thermal shutdown temperature (130°C)', 'Shrinks at elevated temps'],
        dataConfidence: 0.99,
    },
    {
        id: 'ceramic-coated-separator',
        name: 'Ceramic-Coated Separator (Al₂O₃)',
        chemistryFamily: 'Ceramic-Coated-Polyolefin',
        componentType: 'separator',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 0,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 3000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 5.0,
            thermalRunawayOnsetTemp: 200,
            operatingTempRange: { min: -40, max: 130 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 750,
            materialCostPerKWh: 7,
            carbonFootprint: 8,
            recyclability: 45,
            criticalMineralDependency: 1.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Higher thermal stability vs plain PE', 'Reduced internal short-circuit risk', 'Better cycle life'],
        weaknesses: ['Higher cost than plain PE separator', 'More complex manufacturing'],
        dataConfidence: 0.90,
    },

    // ── Current Collectors ────────────────────────────────────────────────────
    {
        id: 'aluminum-current-collector',
        name: 'Aluminum Current Collector (Cathode)',
        chemistryFamily: 'Aluminum',
        componentType: 'current-collector',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 3.77e7,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 5000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 10.0,
            thermalRunawayOnsetTemp: 660,
            operatingTempRange: { min: -60, max: 200 },
            volumeExpansion: 0.5,
            structuralStrengthToWeight: 800,
            materialCostPerKWh: 2,
            carbonFootprint: 10,
            recyclability: 95,
            criticalMineralDependency: 1.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Industry standard for cathode side', 'Excellent conductivity', '95% recyclable'],
        weaknesses: ['Corrodes at anode potentials — cathode use only'],
        dataConfidence: 0.99,
    },
    {
        id: 'copper-current-collector',
        name: 'Copper Current Collector (Anode)',
        chemistryFamily: 'Copper',
        componentType: 'current-collector',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 5.96e7,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 5000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 10.0,
            thermalRunawayOnsetTemp: 1085,
            operatingTempRange: { min: -60, max: 250 },
            volumeExpansion: 0.3,
            structuralStrengthToWeight: 750,
            materialCostPerKWh: 4,
            carbonFootprint: 14,
            recyclability: 90,
            criticalMineralDependency: 3.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Highest electrical conductivity', 'Industry standard for anode side', 'Highly recyclable'],
        weaknesses: ['Heavier than aluminum', 'Higher critical mineral dependency', 'Oxidizes at high voltage — anode use only'],
        dataConfidence: 0.99,
    },

    // ── Casing ────────────────────────────────────────────────────────────────
    {
        id: 'steel-casing',
        name: 'Steel Can (18650/21700)',
        chemistryFamily: 'Steel',
        componentType: 'casing',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 0,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 5000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 10.0,
            thermalRunawayOnsetTemp: 1500,
            operatingTempRange: { min: -60, max: 200 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 850,
            materialCostPerKWh: 3,
            carbonFootprint: 18,
            recyclability: 92,
            criticalMineralDependency: 1.5,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Maximum structural rigidity', 'Excellent puncture resistance', 'Very high recyclability'],
        weaknesses: ['Heaviest casing option — energy density penalty', 'Poor thermal conductivity outward'],
        dataConfidence: 0.99,
    },
    {
        id: 'aluminum-casing',
        name: 'Aluminum Can / Prismatic',
        chemistryFamily: 'Aluminum-Casing',
        componentType: 'casing',
        metrics: {
            gravimetricEnergyDensity: 0,
            volumetricEnergyDensity: 0,
            specificCapacity: 0,
            ionicConductivity: 0,
            coulombicEfficiency: 100,
            cycleLifeTo80SOH: 4000,
            calendarLifeSelfDischarge: 0,
            cRateCapability: 10.0,
            thermalRunawayOnsetTemp: 660,
            operatingTempRange: { min: -60, max: 150 },
            volumeExpansion: 0,
            structuralStrengthToWeight: 920,
            materialCostPerKWh: 4,
            carbonFootprint: 12,
            recyclability: 95,
            criticalMineralDependency: 1.0,
            regulatoryCompliance: { un383: true, reach: true, rohs: true, euBatteryRegulation: true },
        },
        strengths: ['Best strength-to-weight ratio', 'Excellent thermal conductivity', '95% recyclable', 'Lighter than steel'],
        weaknesses: ['Lower strength than steel under impact', 'More expensive than steel'],
        dataConfidence: 0.97,
    },
];

/** Quick lookup by component type */
export function getMaterialsByComponent(
    componentType: RankedMaterial['componentType'],
): typeof CANDIDATE_MATERIALS {
    return CANDIDATE_MATERIALS.filter(m => m.componentType === componentType);
}

/** Quick lookup by id */
export function getMaterialById(id: string): typeof CANDIDATE_MATERIALS[0] | undefined {
    return CANDIDATE_MATERIALS.find(m => m.id === id);
}

/** All supported chemistry families */
export const CHEMISTRY_FAMILIES = [
    'NMC', 'NCA', 'LFP', 'LMFP', 'LNMO', 'Graphite', 'Silicon-Composite', 'Silicon', 'LTO', 'Lithium-Metal',
    'Liquid-Carbonate', 'Solid-State', 'Solid-Polymer', 'Polyolefin', 'Ceramic-Coated-Polyolefin',
    'Aluminum', 'Copper', 'Steel', 'Aluminum-Casing',
] as const;
