'use client';

import React, { useState, useCallback, useEffect, useMemo } from 'react';
import { useTheme, useWidgetSDK, useWidgetState, useMaxHeight } from '@nitrostack/widgets';
import { DESIGN, getPhaseColor } from '../components/design-tokens';
import { PhaseBadge, ToolChip, StatusDot, StatusIndicator, Card, Input, Button, Badge, Separator } from '../components/ui';

interface Section {
  name: string;
  title: string;
  status: 'pending' | 'synced' | 'modified' | 'error';
  wordCount: number;
  lastSync?: string;
  autoGenerated?: boolean;
}

interface Bibliography {
  entries: number;
  status: 'pending' | 'synced' | 'modified';
}

interface OverleafProject {
  projectId: string | null;
  projectUrl: string | null;
  status: 'idle' | 'creating' | 'syncing' | 'synced' | 'error';
  sections: Section[];
  bibliography: Bibliography;
  limitationsSource: 'reviewer_objections' | 'manual' | 'gap_analysis';
  lastFullSync?: string;
}

interface WidgetData {
  project: OverleafProject;
  [key: string]: unknown;
}

interface WidgetState {
  project: OverleafProject;
  expandedSection: string | null;
  syncStatus: 'idle' | 'syncing' | 'success' | 'error';
  syncMessage: string;
  showCreateDialog: boolean;
  newProjectTitle: string;
  newProjectTemplate: 'ieee' | 'acm' | 'neurips' | 'icml' | 'custom';
}

const DEFAULT_SECTIONS: Section[] = [
  { name: 'abstract', title: 'Abstract', status: 'pending', wordCount: 0 },
  { name: 'introduction', title: 'Introduction', status: 'pending', wordCount: 0 },
  { name: 'related-work', title: 'Related Work', status: 'pending', wordCount: 0 },
  { name: 'methodology', title: 'Methodology', status: 'pending', wordCount: 0 },
  { name: 'experiments', title: 'Experiments', status: 'pending', wordCount: 0 },
  { name: 'results', title: 'Results', status: 'pending', wordCount: 0 },
  { name: 'discussion', title: 'Discussion', status: 'pending', wordCount: 0 },
  { name: 'limitations', title: 'Limitations', status: 'pending', wordCount: 0, autoGenerated: false },
  { name: 'conclusion', title: 'Conclusion', status: 'pending', wordCount: 0 },
];

const MOCK_SYNCED_PROJECT: OverleafProject = {
  projectId: 'fl_proj_1785024096407',
  projectUrl: 'https://www.overleaf.com/project/fl_proj_1785024096407',
  status: 'synced',
  sections: [
    { name: 'abstract', title: 'Abstract', status: 'synced', wordCount: 180, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'introduction', title: 'Introduction', status: 'synced', wordCount: 420, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'related-work', title: 'Related Work', status: 'synced', wordCount: 890, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'methodology', title: 'Methodology', status: 'synced', wordCount: 1200, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'experiments', title: 'Experiments', status: 'synced', wordCount: 950, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'results', title: 'Results', status: 'synced', wordCount: 780, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'discussion', title: 'Discussion', status: 'synced', wordCount: 620, lastSync: '2026-07-25T22:35:00Z' },
    { name: 'limitations', title: 'Limitations', status: 'synced', wordCount: 340, lastSync: '2026-07-25T22:35:00Z', autoGenerated: true },
    { name: 'conclusion', title: 'Conclusion', status: 'synced', wordCount: 280, lastSync: '2026-07-25T22:35:00Z' },
  ],
  bibliography: { entries: 14, status: 'synced' },
  limitationsSource: 'reviewer_objections',
  lastFullSync: '2026-07-25T22:35:00Z',
};

const MOCK_IDLE_PROJECT: OverleafProject = {
  projectId: null,
  projectUrl: null,
  status: 'idle',
  sections: DEFAULT_SECTIONS,
  bibliography: { entries: 0, status: 'pending' },
  limitationsSource: 'reviewer_objections',
};

function formatTime(iso: string) {
  const date = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function getStatusColor(status: Section['status']) {
  switch (status) {
    case 'synced': return DESIGN.colors.green;
    case 'modified': return DESIGN.colors.amber;
    case 'error': return DESIGN.colors.red;
    default: return DESIGN.colors.fgDim;
  }
}

function getProjectStatusColor(status: OverleafProject['status']) {
  switch (status) {
    case 'synced': return DESIGN.colors.green;
    case 'syncing': return DESIGN.colors.blue;
    case 'creating': return DESIGN.colors.blue;
    case 'error': return DESIGN.colors.red;
    default: return DESIGN.colors.fgDim;
  }
}

export default function OverleafFlowButton() {
  const theme = useTheme();
  const maxHeight = useMaxHeight();
  const isDark = theme === 'dark';
  const sdk = useWidgetSDK();
  const widgetData = sdk.getToolOutput<WidgetData>();

  // Persistent widget state
  const [state, setState] = useWidgetState<WidgetState>(() => ({
    project: MOCK_IDLE_PROJECT,
    expandedSection: null,
    syncStatus: 'idle',
    syncMessage: '',
    showCreateDialog: false,
    newProjectTitle: '',
    newProjectTemplate: 'ieee',
  }));

  // Initialize from widget data if available
  useEffect(() => {
    if (widgetData?.project) {
      setState(prev => ({ ...prev, project: widgetData.project }));
    }
  }, [widgetData]);

  const project = state.project;
  const isProjectCreated = !!project.projectId;
  const totalWords = project.sections.reduce((sum, s) => sum + s.wordCount, 0);
  const syncedSections = project.sections.filter(s => s.status === 'synced').length;
  const modifiedSections = project.sections.filter(s => s.status === 'modified').length;
  const pendingSections = project.sections.filter(s => s.status === 'pending').length;

  const handleCreateProject = useCallback(async () => {
    if (!state.newProjectTitle.trim()) return;

    setState(prev => ({ ...prev, project: { ...prev.project, status: 'creating' }, syncMessage: 'Creating Overleaf project...' }));

    // Simulate API call
    await new Promise(r => setTimeout(r, 1500));

    const newProject: OverleafProject = {
      projectId: `proj_${Date.now()}`,
      projectUrl: `https://www.overleaf.com/project/proj_${Date.now()}`,
      status: 'synced',
      sections: DEFAULT_SECTIONS.map(s => ({ ...s, status: 'pending' as const })),
      bibliography: { entries: 0, status: 'pending' },
      limitationsSource: 'reviewer_objections',
    };

    setState(prev => ({
      ...prev,
      project: newProject,
      showCreateDialog: false,
      newProjectTitle: '',
      syncMessage: 'Project created successfully!',
      syncStatus: 'success',
    }));

    setTimeout(() => setState(prev => ({ ...prev, syncStatus: 'idle', syncMessage: '' })), 3000);
  }, [state.newProjectTitle]);

  const handleFullSync = useCallback(async () => {
    setState(prev => ({ ...prev, syncStatus: 'syncing', syncMessage: 'Syncing all sections to Overleaf...' }));

    // Simulate sync
    await new Promise(r => setTimeout(r, 2000));

    const syncedSections = project.sections.map(s => ({
      ...s,
      status: 'synced' as const,
      lastSync: new Date().toISOString(),
    }));

    setState(prev => ({
      ...prev,
      project: {
        ...prev.project,
        status: 'synced',
        sections: syncedSections,
        bibliography: { ...prev.project.bibliography, status: 'synced' },
        lastFullSync: new Date().toISOString(),
      },
      syncStatus: 'success',
      syncMessage: `Synced ${syncedSections.length} sections + bibliography`,
    }));

    setTimeout(() => setState(prev => ({ ...prev, syncStatus: 'idle', syncMessage: '' })), 3000);
  }, [project.sections]);

  const handleSyncSection = useCallback(async (sectionName: string) => {
    setState(prev => ({ ...prev, syncStatus: 'syncing', syncMessage: `Syncing ${sectionName}...` }));

    await new Promise(r => setTimeout(r, 800));

    setState(prev => ({
      ...prev,
      project: {
        ...prev.project,
        sections: prev.project.sections.map(s =>
          s.name === sectionName ? { ...s, status: 'synced' as const, lastSync: new Date().toISOString() } : s
        ),
      },
      syncStatus: 'success',
      syncMessage: `Synced ${sectionName}`,
    }));

    setTimeout(() => setState(prev => ({ ...prev, syncStatus: 'idle', syncMessage: '' })), 2000);
  }, []);

  const handleOpenOverleaf = useCallback(() => {
    if (project.projectUrl) {
      window.open(project.projectUrl, '_blank');
    }
  }, [project.projectUrl]);

  const handlePullLimitations = useCallback(async () => {
    setState(prev => ({ ...prev, syncStatus: 'syncing', syncMessage: 'Pulling reviewer objections...' }));

    await new Promise(r => setTimeout(r, 1200));

    setState(prev => ({
      ...prev,
      project: {
        ...prev.project,
        sections: prev.project.sections.map(s =>
          s.name === 'limitations' ? { ...s, status: 'synced' as const, wordCount: 340, autoGenerated: true, lastSync: new Date().toISOString() } : s
        ),
      },
      syncStatus: 'success',
      syncMessage: 'Pulled 3 reviewer objections as limitations',
    }));

    setTimeout(() => setState(prev => ({ ...prev, syncStatus: 'idle', syncMessage: '' })), 3000);
  }, []);

  const handleExportZip = useCallback(async () => {
    setState(prev => ({ ...prev, syncStatus: 'syncing', syncMessage: 'Exporting Overleaf project as ZIP...' }));

    await new Promise(r => setTimeout(r, 1500));

    setState(prev => ({
      ...prev,
      syncStatus: 'success',
      syncMessage: 'ZIP exported to Downloads',
    }));

    setTimeout(() => setState(prev => ({ ...prev, syncStatus: 'idle', syncMessage: '' })), 3000);
  }, []);

  const toggleSection = useCallback((sectionName: string) => {
    setState(prev => ({ ...prev, expandedSection: prev.expandedSection === sectionName ? null : sectionName }));
  }, []);

  // Compact "Create Project" view
  if (!isProjectCreated) {
    return (
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          height: '100%',
          maxHeight: maxHeight ?? undefined,
          width: '100%',
          backgroundColor: DESIGN.colors.bg,
          borderRight: `1px solid ${DESIGN.colors.border}`,
          fontFamily: DESIGN.fonts.sans,
          color: DESIGN.colors.fg,
          overflow: 'hidden',
        }}
      >
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: DESIGN.spacing.xl }}>
          <Card
            elevated
            padding="xl"
            style={{ maxWidth: 360, width: '100%', textAlign: 'center' }}
          >
            <div style={{
              width: 64, height: 64, borderRadius: '50%',
              backgroundColor: `${DESIGN.colors.amber}20`,
              border: `1px solid ${DESIGN.colors.amber}60`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              margin: `0 auto ${DESIGN.spacing.lg}px`,
            }}>
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.amber} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
            </div>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: DESIGN.colors.fg, margin: `${DESIGN.spacing.md}px 0 ${DESIGN.spacing.xs}px` }}>
              Connect to Overleaf
            </h2>
            <p style={{ fontSize: 13, color: DESIGN.colors.fgMuted, margin: 0, lineHeight: 1.5 }}>
              Create a new paper project from our IEEE template or sync an existing Overleaf project.
            </p>

            <Button
              variant="primary"
              size="lg"
              onClick={() => setState(prev => ({ ...prev, showCreateDialog: true }))}
              style={{ width: '100%', marginTop: DESIGN.spacing.lg, padding: '12px 24px', fontSize: 14 }}
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 8 }}>
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
              Create New Project
            </Button>

            <Button
              variant="secondary"
              size="md"
              onClick={() => console.log('Connect existing project')}
              style={{ width: '100%', marginTop: DESIGN.spacing.sm }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 8 }}>
                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                <polyline points="15 3 21 3 21 9" />
                <line x1="10" y1="14" x2="21" y2="3" />
              </svg>
              Connect Existing Project
            </Button>

            <details style={{ marginTop: DESIGN.spacing.lg, textAlign: 'left' }}>
              <summary style={{ fontSize: 11, fontWeight: 600, color: DESIGN.colors.fgMuted, textTransform: 'uppercase', letterSpacing: 0.5, fontFamily: DESIGN.fonts.mono, cursor: 'pointer' }}>
                What happens next?
              </summary>
              <ul style={{ fontSize: 11, color: DESIGN.colors.fgMuted, marginTop: DESIGN.spacing.sm, paddingLeft: DESIGN.spacing.lg, lineHeight: 2 }}>
                <li>Creates Overleaf project from IEEE template</li>
                <li>Sets up 9 standard sections + bibliography</li>
                <li>Auto-generates Limitations from reviewer objections</li>
                <li>One-click sync for each section</li>
                <li>Full project ZIP export available</li>
              </ul>
            </details>
          </Card>
        </div>
      </div>
    );
  }

  // Expanded Project View
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        maxHeight: maxHeight ?? undefined,
        width: '100%',
        maxWidth: 520,
        backgroundColor: DESIGN.colors.bg,
        borderRight: `1px solid ${DESIGN.colors.border}`,
        fontFamily: DESIGN.fonts.sans,
        color: DESIGN.colors.fg,
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div style={{
        padding: `${DESIGN.spacing.md}px ${DESIGN.spacing.lg}px`,
        borderBottom: `1px solid ${DESIGN.colors.border}`,
        backgroundColor: DESIGN.colors.bgElevated,
      }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: DESIGN.spacing.md }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm, marginBottom: DESIGN.spacing.xs }}>
              <div style={{
                width: 32, height: 32, borderRadius: DESIGN.radius.md,
                backgroundColor: `${DESIGN.colors.green}20`,
                border: `1px solid ${DESIGN.colors.green}60`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.green} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                  <line x1="16" y1="13" x2="8" y2="13" />
                  <line x1="16" y1="17" x2="8" y2="17" />
                  <polyline points="10 9 9 9 8 9" />
                </svg>
              </div>
              <div style={{ minWidth: 0 }}>
                <h2 style={{ fontSize: 14, fontWeight: 700, color: DESIGN.colors.fg, margin: 0, lineHeight: 1.2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {project.projectId}
                </h2>
                <div style={{ display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm, marginTop: 2 }}>
                  <StatusDot status={project.status} size={6} />
                  <span style={{ fontSize: 11, color: DESIGN.colors.fgDim, fontFamily: DESIGN.fonts.mono }}>
                    {syncedSections}/{project.sections.length} sections • {totalWords.toLocaleString()} words
                  </span>
                </div>
              </div>
            </div>
            {project.lastFullSync && (
              <span style={{ fontSize: 10, color: DESIGN.colors.fgDim, fontFamily: DESIGN.fonts.mono }}>
                Last full sync: {formatTime(project.lastFullSync)}
              </span>
            )}
          </div>
          <div style={{ display: 'flex', gap: DESIGN.spacing.xs, flexShrink: 0 }}>
            <Button variant="ghost" size="sm" onClick={handleOpenOverleaf} disabled={!project.projectUrl}>
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                <polyline points="15 3 21 3 21 9" />
                <line x1="10" y1="14" x2="21" y2="3" />
              </svg>
              Open
            </Button>
            <Button variant="secondary" size="sm" onClick={handleExportZip} loading={state.syncStatus === 'syncing'}>
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Export ZIP
            </Button>
          </div>
        </div>
      </div>

      {/* Sync Status Bar */}
      {(state.syncStatus === 'syncing' || state.syncStatus === 'success' || state.syncStatus === 'error') && (
        <div style={{
          padding: `${DESIGN.spacing.xs}px ${DESIGN.spacing.lg}px`,
          backgroundColor: state.syncStatus === 'syncing' ? `${DESIGN.colors.blue}15` :
                           state.syncStatus === 'success' ? `${DESIGN.colors.green}15` :
                           `${DESIGN.colors.red}15`,
          borderBottom: `1px solid ${
            state.syncStatus === 'syncing' ? `${DESIGN.colors.blue}40` :
            state.syncStatus === 'success' ? `${DESIGN.colors.green}40` :
            `${DESIGN.colors.red}40`
          }`,
          display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm,
        }}>
          {state.syncStatus === 'syncing' && (
            <span style={{ width: 12, height: 12, borderRadius: '50%', border: `2px solid ${DESIGN.colors.blue}40`, borderTopColor: DESIGN.colors.blue, animation: 'spin 0.8s linear infinite', display: 'inline-block' }} />
          )}
          {state.syncStatus === 'success' && (
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.green} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
          )}
          {state.syncStatus === 'error' && (
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.red} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10" /><line x1="15" y1="9" x2="9" y2="15" /><line x1="9" y1="9" x2="15" y2="15" /></svg>
          )}
          <span style={{ fontSize: 11, fontFamily: DESIGN.fonts.mono, fontWeight: 500 }}>
            {state.syncMessage}
          </span>
        </div>
      )}

      {/* Quick Actions */}
      <div style={{
        padding: `${DESIGN.spacing.sm}px ${DESIGN.spacing.lg}px`,
        borderBottom: `1px solid ${DESIGN.colors.border}`,
        backgroundColor: DESIGN.colors.bgElevated,
      }}>
        <div style={{ display: 'flex', gap: DESIGN.spacing.xs, flexWrap: 'wrap' }}>
          <Button
            variant={project.status === 'synced' ? 'primary' : 'secondary'}
            size="sm"
            onClick={handleFullSync}
            loading={state.syncStatus === 'syncing'}
            disabled={project.sections.every(s => s.status === 'synced') && project.bibliography.status === 'synced'}
            style={{ fontSize: 11 }}
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
              <polyline points="23 4 23 10 17 10" />
              <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
            </svg>
            Full Sync
          </Button>
          {project.limitationsSource === 'reviewer_objections' && (
            <Button
              variant="secondary"
              size="sm"
              onClick={handlePullLimitations}
              loading={state.syncStatus === 'syncing'}
              style={{ fontSize: 11 }}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Pull Limitations
            </Button>
          )}
          <Button
            variant="ghost"
            size="sm"
            onClick={() => console.log('Open bibliography manager')}
            style={{ fontSize: 11, marginLeft: 'auto' }}
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>
            Bibliography ({project.bibliography.entries})
          </Button>
        </div>
      </div>

      {/* Sections Grid */}
      <div style={{ flex: 1, overflowY: 'auto', padding: DESIGN.spacing.md }}>
        <div style={{ marginBottom: DESIGN.spacing.md }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: DESIGN.spacing.sm }}>
            <span style={{ fontSize: 11, fontWeight: 600, color: DESIGN.colors.fgMuted, textTransform: 'uppercase', letterSpacing: 0.5, fontFamily: DESIGN.fonts.mono }}>
              Paper Sections
            </span>
            <div style={{ display: 'flex', gap: DESIGN.spacing.xs }}>
              <Badge variant={syncedSections > 0 ? 'success' : 'default'} size="sm">
                {syncedSections} synced
              </Badge>
              <Badge variant={modifiedSections > 0 ? 'warning' : 'default'} size="sm">
                {modifiedSections} modified
              </Badge>
              <Badge variant={pendingSections > 0 ? 'info' : 'default'} size="sm">
                {pendingSections} pending
              </Badge>
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: DESIGN.spacing.sm }}>
            {project.sections.map(section => (
              <SectionCard
                key={section.name}
                section={section}
                isExpanded={state.expandedSection === section.name}
                onToggle={() => toggleSection(section.name)}
                onSync={() => handleSyncSection(section.name)}
                projectStatus={project.status}
              />
            ))}
          </div>
        </div>

        {/* Bibliography Card */}
        <Card elevated padding="md" style={{ borderColor: DESIGN.colors.border }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm }}>
              <div style={{
                width: 36, height: 36, borderRadius: DESIGN.radius.md,
                backgroundColor: `${DESIGN.colors.phaseExport}20`,
                border: `1px solid ${DESIGN.colors.phaseExport}60`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.phaseExport} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
                  <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
                  <line x1="10" y1="9" x2="18" y2="9" />
                  <line x1="10" y1="13" x2="14" y2="13" />
                  <line x1="10" y1="17" x2="12" y2="17" />
                </svg>
              </div>
              <div>
                <div style={{ fontSize: 13, fontWeight: 600, color: DESIGN.colors.fg }}>Bibliography</div>
                <div style={{ fontSize: 11, color: DESIGN.colors.fgMuted, fontFamily: DESIGN.fonts.mono }}>
                  {project.bibliography.entries} entries • {project.bibliography.status}
                </div>
              </div>
            </div>
            <Button variant="ghost" size="sm" onClick={() => console.log('Manage bibliography')}>
              Manage
            </Button>
          </div>
        </Card>
      </div>

      {/* Limitations Source Info */}
      <div style={{
        padding: DESIGN.spacing.md,
        borderTop: `1px solid ${DESIGN.colors.border}`,
        backgroundColor: DESIGN.colors.bgElevated,
      }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: DESIGN.spacing.sm }}>
          <div style={{
            width: 28, height: 28, borderRadius: DESIGN.radius.sm,
            backgroundColor: `${DESIGN.colors.phaseStretch}20`,
            border: `1px solid ${DESIGN.colors.phaseStretch}60`,
            display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={DESIGN.colors.phaseStretch} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: DESIGN.colors.fg }}>Limitations Source</div>
            <div style={{ fontSize: 10, color: DESIGN.colors.fgMuted, fontFamily: DESIGN.fonts.mono, marginTop: 2 }}>
              {project.limitationsSource === 'reviewer_objections' && 'Auto-generated from reviewer objections'}
              {project.limitationsSource === 'gap_analysis' && 'Generated from gap analysis findings'}
              {project.limitationsSource === 'manual' && 'Manually written'}
            </div>
            <div style={{ display: 'flex', gap: DESIGN.spacing.xs, marginTop: DESIGN.spacing.sm, flexWrap: 'wrap' }}>
              <Button variant="ghost" size="sm" onClick={() => console.log('Change to reviewer')}>
                <Badge variant={project.limitationsSource === 'reviewer_objections' ? 'success' : 'default'} size="sm">
                  Reviewer Objections
                </Badge>
              </Button>
              <Button variant="ghost" size="sm" onClick={() => console.log('Change to gap')}>
                <Badge variant={project.limitationsSource === 'gap_analysis' ? 'success' : 'default'} size="sm">
                  Gap Analysis
                </Badge>
              </Button>
              <Button variant="ghost" size="sm" onClick={() => console.log('Change to manual')}>
                <Badge variant={project.limitationsSource === 'manual' ? 'success' : 'default'} size="sm">
                  Manual
                </Badge>
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Create Project Dialog */}
      {state.showCreateDialog && (
        <div
          style={{
            position: 'fixed', inset: 0, zIndex: DESIGN.zIndex.modal,
            backgroundColor: 'rgba(0,0,0,0.7)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: DESIGN.spacing.lg,
          }}
          onClick={() => setState(prev => ({ ...prev, showCreateDialog: false }))}
        >
        <Card elevated padding="xl" style={{ width: '100%', maxWidth: 440, backgroundColor: DESIGN.colors.bgElevated }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: DESIGN.spacing.lg }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: DESIGN.colors.fg, margin: 0 }}>Create Overleaf Project</h2>
            <Button variant="ghost" size="sm" onClick={() => setState(prev => ({ ...prev, showCreateDialog: false }))}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </Button>
          </div>

          <Input
            label="Project Title"
            placeholder="e.g., Adaptive Differential Privacy for Federated Learning"
            value={state.newProjectTitle}
            onChange={(e) => setState(prev => ({ ...prev, newProjectTitle: e.target.value }))}
            style={{ marginBottom: DESIGN.spacing.md }}
          />

          <div style={{ marginBottom: DESIGN.spacing.md }}>
            <label style={{ fontSize: 11, fontWeight: 600, color: DESIGN.colors.fgMuted, textTransform: 'uppercase', letterSpacing: 0.5, fontFamily: DESIGN.fonts.mono, display: 'block', marginBottom: DESIGN.spacing.xs }}>
              Template
            </label>
            <div style={{ display: 'flex', flexDirection: 'column', gap: DESIGN.spacing.xs }}>
              {(['ieee', 'acm', 'neurips', 'icml'] as const).map(template => (
                <label key={template} style={{
                  display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm,
                  padding: `${DESIGN.spacing.sm}px ${DESIGN.spacing.md}px`,
                  backgroundColor: state.newProjectTemplate === template ? `${DESIGN.colors.amber}20` : DESIGN.colors.bg,
                  border: `1px solid ${state.newProjectTemplate === template ? DESIGN.colors.amber : DESIGN.colors.border}`,
                  borderRadius: DESIGN.radius.md,
                  cursor: 'pointer', transition: DESIGN.transitions.fast,
                }}>
                  <input
                    type="radio"
                    name="template"
                    value={template}
                    checked={state.newProjectTemplate === template}
                    onChange={() => setState(prev => ({ ...prev, newProjectTemplate: template }))}
                    style={{ accentColor: DESIGN.colors.amber }}
                  />
                  <div>
                    <div style={{ fontSize: 12, fontWeight: 600, color: DESIGN.colors.fg, textTransform: 'uppercase' }}>
                      {template.toUpperCase()}
                    </div>
                    <div style={{ fontSize: 10, color: DESIGN.colors.fgDim }}>
                      {template === 'ieee' && 'IEEE conference format (2-column)'}
                      {template === 'acm' && 'ACM conference format (2-column)'}
                      {template === 'neurips' && 'NeurIPS format (1-column)'}
                      {template === 'icml' && 'ICML format (1-column)'}
                    </div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          <div style={{ display: 'flex', gap: DESIGN.spacing.sm, justifyContent: 'flex-end' }}>
            <Button variant="secondary" onClick={() => setState(prev => ({ ...prev, showCreateDialog: false }))}>
              Cancel
            </Button>
            <Button variant="primary" onClick={handleCreateProject} disabled={!state.newProjectTitle.trim()} loading={state.syncStatus === 'syncing'}>
              Create Project
            </Button>
          </div>
        </Card>
      </div>
    )}
    </div>
  );
}

function SectionCard({ section, isExpanded, onToggle, onSync, projectStatus }: {
  section: Section;
  isExpanded: boolean;
  onToggle: () => void;
  onSync: () => void;
  projectStatus: OverleafProject['status'];
}) {
  const statusColor = getStatusColor(section.status);
  const canSync = section.status !== 'synced' && projectStatus === 'synced';

  return (
    <Card
      elevated={isExpanded}
      padding="sm"
      onClick={onToggle}
      style={{
        borderColor: isExpanded ? statusColor : (section.status === 'synced' ? `${DESIGN.colors.green}60` : DESIGN.colors.border),
        cursor: 'pointer',
        position: 'relative',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: DESIGN.spacing.sm }}>
        <div style={{
          width: 8, height: 8, borderRadius: '50%',
          backgroundColor: statusColor,
          marginTop: 3, flexShrink: 0,
          boxShadow: section.status === 'synced' ? `0 0 8px ${statusColor}` : 'none',
        }} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: DESIGN.spacing.xs }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: DESIGN.spacing.xs, minWidth: 0 }}>
              <h4 style={{ fontSize: 12, fontWeight: 600, color: DESIGN.colors.fg, margin: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                {section.title}
              </h4>
              {section.autoGenerated && (
                <Badge variant="info" size="sm" style={{ fontSize: 9 }}>
                  Auto
                </Badge>
              )}
            </div>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ color: DESIGN.colors.fgDim, flexShrink: 0, transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)', transition: DESIGN.transitions.fast }}>
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: DESIGN.spacing.sm, marginTop: DESIGN.spacing.xs, flexWrap: 'wrap' }}>
            <StatusIndicator status={section.status} style={{ fontSize: 10 }} />
            {section.wordCount > 0 && (
              <span style={{ fontSize: 10, color: DESIGN.colors.fgDim, fontFamily: DESIGN.fonts.mono }}>
                {section.wordCount.toLocaleString()} words
              </span>
            )}
            {section.lastSync && (
              <span style={{ fontSize: 10, color: DESIGN.colors.fgDim, fontFamily: DESIGN.fonts.mono }}>
                {formatTime(section.lastSync)}
              </span>
            )}
          </div>
        </div>
      </div>

      {isExpanded && (
        <div style={{ marginTop: DESIGN.spacing.sm, paddingTop: DESIGN.spacing.sm, borderTop: `1px solid ${DESIGN.colors.border}`, display: 'flex', gap: DESIGN.spacing.xs, justifyContent: 'flex-end' }}>
          <Button
            variant={canSync ? 'primary' : 'ghost'}
            size="sm"
            onClick={(e) => { e.stopPropagation(); onSync(); }}
            disabled={!canSync || section.status === 'synced'}
            loading={false}
            style={{ fontSize: 10 }}
          >
            {section.status === 'synced' ? (
              <>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                  <polyline points="20 6 9 17 4 12" />
                </svg>
                Synced
              </>
            ) : section.status === 'modified' ? (
              <>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                  <polyline points="23 4 23 10 17 10" />
                  <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
                </svg>
                Re-sync
              </>
            ) : (
              <>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: 4 }}>
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
                Sync
              </>
            )}
          </Button>
        </div>
      )}
    </Card>
  );
}