export type ConnectionStatus = 'connecting' | 'connected' | 'reconnecting' | 'disconnected';
export interface MachineHealth { machineId:string; machineName:string; productionLine:string; status:string; healthScore:number; telemetry?:{temperature?:number; vibration?:number; pressure?:number}; alert?:{severity:string; message:string}; lastUpdatedAt:string; }
export interface InventoryResult { partId:string; partName:string; requiredQuantity:number; availableQuantity:number; reservedQuantity:number; reorderLevel:number; storageLocation:string; stockStatus:string; purchaseRequired:boolean; }
export interface SupplierOption { supplierId:string; supplierName:string; unitPrice:number; quantity:number; shippingCost:number; totalCost:number; deliveryHours:number; rating:number; reliabilityScore:number; supplierStatus:string; recommended:boolean; recommendationReason?:string; }
export interface SupplierComparison { partId:string; currency?:string; suppliers:SupplierOption[]; }
export interface ProductionChange { orderId:string; priority:string; product?:string; action:string; fromMachine:string; toMachine:string; originalStartTime:string; originalEndTime:string; revisedStartTime:string; revisedEndTime:string; scheduleDelayHours:number; customerDelayHours:number; reason:string; }
export interface ProductionPlanView { planId:string; machineId:string; alternateMachine?:string; alternateMachineLoad?:number; changes:ProductionChange[]; }
export interface ApprovalView { approvalId:string; workflowId?:string; amount:number; threshold:number; currency:string; status:string; decidedBy?:string; decidedAt?:string; report:any; }
export interface WorkflowKpis { workflowId:string; machineId:string; currentStage:string; status:string; progressPercent?:number; startedAt?:string; estimatedRecoveryTime?:string; updatedAt:string; history?:Array<{stage:string;enteredAt:string}>; financialImpact?:Record<string,number|null>; productionImpact?:Record<string,number>; notifications?:Record<string,string>; alerts?:Array<{alertId:string;status:string;severity:string;stage:string}>; }
export interface FactoryDashboardState { machineHealth:MachineHealth|null; inventory:InventoryResult|null; suppliers:SupplierComparison|null; productionPlan:ProductionPlanView|null; approval:ApprovalView|null; workflowKpis:WorkflowKpis|null; connectionStatus:ConnectionStatus; error?:string; }
export interface FactorySocketEvent { type:string; eventType?:string; sequence?:number; workflowId?:string; notification?:any; workflow?:any; alert?:any; payload?:any; }
