/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CreditScoreRouteImport } from './routes/credit-score'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TransferDomesticRouteImport } from './routes/transfer-domestic'
import { Route as TransferInternationalRouteImport } from './routes/transfer-international'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSessionIdRouteImport } from './routes/admin.session.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditScoreRoute = CreditScoreRouteImport.update({
  id: '/credit-score',
  path: '/credit-score',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferDomesticRoute = TransferDomesticRouteImport.update({
  id: '/transfer-domestic',
  path: '/transfer-domestic',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferInternationalRoute = TransferInternationalRouteImport.update({
  id: '/transfer-international',
  path: '/transfer-international',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionIdRoute = AdminSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/branches': typeof BranchesRoute
  '/credit-score': typeof CreditScoreRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/transfer-domestic': typeof TransferDomesticRoute
  '/transfer-international': typeof TransferInternationalRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/session/$id': typeof AdminSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/credit-score': typeof CreditScoreRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/transfer-domestic': typeof TransferDomesticRoute
  '/transfer-international': typeof TransferInternationalRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/session/$id': typeof AdminSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/branches': typeof BranchesRoute
  '/credit-score': typeof CreditScoreRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/transfer-domestic': typeof TransferDomesticRoute
  '/transfer-international': typeof TransferInternationalRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/session/$id': typeof AdminSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/branches'
    | '/credit-score'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/transfer-domestic'
    | '/transfer-international'
    | '/withdraw'
    | '/admin/analytics'
    | '/admin/'
    | '/admin/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/credit-score'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/transfer-domestic'
    | '/transfer-international'
    | '/withdraw'
    | '/admin/analytics'
    | '/admin'
    | '/admin/session/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/branches'
    | '/credit-score'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/transfer-domestic'
    | '/transfer-international'
    | '/withdraw'
    | '/admin/analytics'
    | '/admin/'
    | '/admin/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BranchesRoute: typeof BranchesRoute
  CreditScoreRoute: typeof CreditScoreRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  LoginRoute: typeof LoginRoute
  TransferDomesticRoute: typeof TransferDomesticRoute
  TransferInternationalRoute: typeof TransferInternationalRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-score': {
      id: '/credit-score'
      path: '/credit-score'
      fullPath: '/credit-score'
      preLoaderRoute: typeof CreditScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-domestic': {
      id: '/transfer-domestic'
      path: '/transfer-domestic'
      fullPath: '/transfer-domestic'
      preLoaderRoute: typeof TransferDomesticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-international': {
      id: '/transfer-international'
      path: '/transfer-international'
      fullPath: '/transfer-international'
      preLoaderRoute: typeof TransferInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/session/$id': {
      id: '/admin/session/$id'
      path: '/session/$id'
      fullPath: '/admin/session/$id'
      preLoaderRoute: typeof AdminSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSessionIdRoute: typeof AdminSessionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSessionIdRoute: AdminSessionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BranchesRoute: BranchesRoute,
  CreditScoreRoute: CreditScoreRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  LoginRoute: LoginRoute,
  TransferDomesticRoute: TransferDomesticRoute,
  TransferInternationalRoute: TransferInternationalRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
