import type { CandidateType } from './types.js';

export const DEFAULT_MHCI_PEPTIDE_LENGTHS = [8, 9, 10, 11] as const;
export const DEFAULT_MHCII_PEPTIDE_LENGTHS = [
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
] as const;

export interface GeneratedPeptide {
  candidateType: 'MHCI' | 'MHCII';
  start: number;
  end: number;
  length: number;
  peptide: string;
}

export function generatePeptides(
  sequence: string,
  candidateType: CandidateType,
  configuredLengths: readonly number[],
): GeneratedPeptide[] {
  if (candidateType === 'BCELL') {
    throw new Error('B-cell regions are not generated by the T-cell sliding-window algorithm');
  }
  if (configuredLengths.some((length) => !Number.isInteger(length) || length <= 0)) {
    throw new RangeError('Peptide lengths must be positive integers');
  }

  const lengths = [...new Set(configuredLengths)].sort((left, right) => left - right);
  const peptides: GeneratedPeptide[] = [];
  for (const length of lengths) {
    if (length > sequence.length) continue;
    for (let start0 = 0; start0 <= sequence.length - length; start0 += 1) {
      peptides.push({
        candidateType,
        start: start0 + 1,
        end: start0 + length,
        length,
        peptide: sequence.slice(start0, start0 + length),
      });
    }
  }

  return peptides.sort(
    (left, right) =>
      left.candidateType.localeCompare(right.candidateType) ||
      left.start - right.start ||
      left.length - right.length ||
      left.peptide.localeCompare(right.peptide),
  );
}
