import { ControllerDecorator as Controller, ToolDecorator as Tool, Widget } from '@nitrostack/core';
import { z } from 'zod';
import { createClient } from '@supabase/supabase-js';

@Controller('documents')
export class DocumentsController {
    @Tool({
        name: 'upload_document',
        description: 'Uploads multiple PDF documents (PYQs, Syllabus, Notes), parses them via LlamaParse, extracts entities using Groq Llama-3, and stores in Supabase.',
        inputSchema: z.object({
            course_name: z.string().describe('The name of the course this document belongs to (e.g. Machine Learning)'),
            files: z.array(z.object({
                document_category: z.enum(['syllabus', 'pyq', 'notes']).describe('The strict category of the document'),
                file_name: z.string().describe('Name of the uploaded file'),
                file_type: z.string().describe('MIME type of the uploaded file'),
                file_content: z.string().describe('Base64 encoded file content'),
            }))
        })
    })
    @Widget('upload')
    async uploadDocument(params: { course_name: string; files: { document_category: string; file_name: string; file_type: string; file_content: string }[] }) {
        const LLAMA_CLOUD_API_KEY = process.env.LLAMA_CLOUD_API_KEY;
        const SUPABASE_URL = process.env.SUPABASE_URL;
        const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
        const GROQ_API_KEY = process.env.GROQ_API_KEY;

        if (!LLAMA_CLOUD_API_KEY || !SUPABASE_URL || !SUPABASE_KEY || !GROQ_API_KEY) {
            throw new Error("Missing required API keys.");
        }

        const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

        // 1. Resolve or Create Course
        let courseId = '';
        const { data: existingCourse } = await supabase.from('courses').select('id').ilike('name', params.course_name).maybeSingle();
        
        if (existingCourse) {
            courseId = existingCourse.id;
        } else {
            const { data: newCourse, error: createError } = await supabase.from('courses').insert({
                name: params.course_name,
                description: `Autogenerated course for ${params.course_name}`
            }).select('id').single();
            
            if (createError) throw new Error("Failed to auto-create course: " + createError.message);
            courseId = newCourse.id;
        }

        const results = [];

        // 2. Loop through each file
        for (const file of params.files) {
            try {
                const base64Data = file.file_content.split(',')[1] || file.file_content;
                const binaryData = Buffer.from(base64Data, 'base64');
                const blob = new Blob([binaryData], { type: 'application/pdf' });
                const formData = new FormData();
                formData.append('file', blob, file.file_name);

                // Send to LlamaParse
                const parseRes = await fetch('https://api.cloud.llamaindex.ai/api/parsing/upload', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${LLAMA_CLOUD_API_KEY}`,
                        'Accept': 'application/json'
                    },
                    body: formData
                });

                if (!parseRes.ok) throw new Error(`LlamaParse Upload Failed: ${parseRes.statusText}`);
                const parseData = await parseRes.json() as any;
                const jobId = parseData.id;

                // Poll for Completion
                let markdownText = "";
                for (let i = 0; i < 20; i++) {
                    await new Promise(resolve => setTimeout(resolve, 3000));
                    const statusRes = await fetch(`https://api.cloud.llamaindex.ai/api/parsing/job/${jobId}`, {
                        headers: { 'Authorization': `Bearer ${LLAMA_CLOUD_API_KEY}` }
                    });
                    const statusData = await statusRes.json() as any;
                    if (statusData.status === 'SUCCESS') {
                        const resultRes = await fetch(`https://api.cloud.llamaindex.ai/api/parsing/job/${jobId}/result/markdown`, {
                            headers: { 'Authorization': `Bearer ${LLAMA_CLOUD_API_KEY}` }
                        });
                        const resultData = await resultRes.json() as any;
                        markdownText = resultData.markdown;
                        break;
                    }
                }

                if (!markdownText) markdownText = "Failed to extract markdown within timeout.";

                // Extract Entities using Groq
                let extractionPrompt = '';
                if (file.document_category === 'syllabus') {
                    extractionPrompt = `Extract the course modules and topics from this syllabus. Return ONLY a valid JSON array of objects with the exact keys: {"module_number": number, "module_name": string, "topic_name": string, "subtopics": string[]}. Syllabus Text: ${markdownText}`;
                } else if (file.document_category === 'pyq') {
                    extractionPrompt = `Extract every question from this Past Year Question paper. Identify the topic it belongs to, the marks awarded, and the question text. Return ONLY a valid JSON array of objects with the exact keys: {"question_text": string, "topic_name": string, "marks": number}. PYQ Text: ${markdownText}`;
                } else {
                    extractionPrompt = `Extract the core topics from these notes. Return ONLY a valid JSON array of objects with the exact keys: {"topic_name": string}. Notes Text: ${markdownText}`;
                }

                const groqRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
                    method: "POST",
                    headers: {
                        "Authorization": `Bearer ${GROQ_API_KEY}`,
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        model: "llama-3.3-70b-versatile",
                        response_format: { type: "json_object" },
                        messages: [
                            { role: "system", content: "You are an expert academic parser. You strictly return JSON arrays wrapped in an object like { \"data\": [...] }." },
                            { role: "user", content: extractionPrompt }
                        ]
                    })
                });

                if (!groqRes.ok) throw new Error("Groq Extraction Failed");
                const groqData = await groqRes.json() as any;
                const extractedJson = JSON.parse(groqData.choices[0].message.content);
                const dataArr = extractedJson.data || extractedJson.topics || extractedJson.questions || [];

                // Store in Supabase
                const { data: docRes, error: docErr } = await supabase.from('documents').insert({
                    course_id: courseId,
                    file_name: file.file_name,
                    file_type: file.document_category,
                    raw_markdown: markdownText,
                    processing_status: 'completed'
                }).select('id').single();

                if (docErr) throw new Error("Supabase insert document failed: " + docErr.message);

                if (file.document_category === 'pyq' && dataArr.length > 0) {
                    const pyqInserts = dataArr.map((q: any) => ({
                        document_id: docRes.id,
                        course_id: courseId,
                        question_text: q.question_text || 'Unknown',
                        topic_name: q.topic_name || 'General',
                        marks: q.marks || 0
                    }));
                    await supabase.from('pyq_questions').insert(pyqInserts);
                }

                results.push({
                    file_name: file.file_name,
                    extracted_items: dataArr.length,
                    document_id: docRes.id
                });
            } catch (err) {
                console.error(`Error processing file ${file.file_name}:`, err);
                results.push({
                    file_name: file.file_name,
                    error: err instanceof Error ? err.message : 'Unknown error'
                });
            }
        }

        return {
            success: true,
            course_name: params.course_name,
            total_files_processed: params.files.length,
            results: results
        };
    }
}
