'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { FileText, Download, ArrowLeft, ShieldAlert, CheckCircle, Calendar, Users } from 'lucide-react';
import Link from 'next/link';

function ReportContent() {
  const searchParams = useSearchParams();
  const projectId = searchParams.get('id') || 'proj_demo_9823';

  const [context, setContext] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function loadData() {
      try {
        const res = await fetch(`/api/project/context?id=${projectId}`);
        if (res.ok) {
          const json = await res.json();
          setContext(json);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [projectId]);

  const handleDownloadMarkdown = () => {
    if (!context) return;
    const content = `# Project Planning Report (${context.project_context_id})
SDLC Model: ${context.selected_sdlc_model || 'Agile-Scrum'}
Duration: ${context.srd_summary?.project_duration_weeks || 8} Weeks

## Extracted Requirements
${context.srd_summary?.parsed_requirements?.map((r: any) => `- [${r.id}] ${r.description}`).join('\n') || 'None'}

## Roadmap Phases
${context.roadmap?.phases?.map((p: any) => `### Phase ${p.phase_number}: ${p.name}\n${p.objectives.join(', ')}`).join('\n') || 'None'}
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Report_${projectId}.md`;
    a.click();
  };

  if (loading) {
    return <div className="p-12 text-center text-slate-400 text-sm">Loading Executive Report...</div>;
  }

  return (
    <div className="max-w-4xl mx-auto p-6 md:p-10 bg-white border border-slate-200 rounded-2xl shadow-sm my-6 space-y-8">
      {/* Top Controls */}
      <div className="flex justify-between items-center border-b border-slate-100 pb-4">
        <Link href="/" className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-800">
          <ArrowLeft size={14} /> Back to Dashboard
        </Link>
        <button
          onClick={handleDownloadMarkdown}
          className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-blue-600 text-white text-xs font-semibold hover:bg-blue-700 transition-colors"
        >
          <Download size={14} /> Download Markdown Report
        </button>
      </div>

      {/* Document Header */}
      <div className="border-b border-slate-100 pb-6">
        <div className="inline-block px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-semibold mb-2">
          Executive Project Planning Deliverable
        </div>
        <h1 className="text-2xl font-bold text-slate-900">Project Architectural & Execution Plan</h1>
        <p className="text-xs text-slate-500 mt-1">Generated by ProjectPilot AI • Session `{projectId}`</p>
      </div>

      {/* Executive Summary */}
      <section className="space-y-3">
        <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700 flex items-center gap-2">
          <FileText size={16} className="text-blue-500" /> Executive Summary
        </h2>
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-100 text-xs text-slate-700 leading-relaxed">
          This project plan outlines the target execution strategy for session <strong>{projectId}</strong>. Based on parsed requirements, the recommended SDLC framework is <strong>{context?.selected_sdlc_model || 'Agile-Scrum'}</strong> over a target timeline of <strong>{context?.srd_summary?.project_duration_weeks || 8} weeks</strong>.
        </div>
      </section>

      {/* Key Metrics */}
      <section className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="p-4 rounded-xl bg-purple-50/50 border border-purple-100">
          <div className="flex items-center gap-2 text-purple-700 text-xs font-semibold mb-1">
            <Calendar size={14} /> Duration
          </div>
          <div className="text-lg font-bold text-slate-800">{context?.srd_summary?.project_duration_weeks || 8} Weeks</div>
        </div>

        <div className="p-4 rounded-xl bg-amber-50/50 border border-amber-100">
          <div className="flex items-center gap-2 text-amber-700 text-xs font-semibold mb-1">
            <CheckCircle size={14} /> Framework
          </div>
          <div className="text-lg font-bold text-slate-800">{context?.selected_sdlc_model || 'Agile-Scrum'}</div>
        </div>

        <div className="p-4 rounded-xl bg-emerald-50/50 border border-emerald-100">
          <div className="flex items-center gap-2 text-emerald-700 text-xs font-semibold mb-1">
            <Users size={14} /> Roster
          </div>
          <div className="text-lg font-bold text-slate-800">{context?.team_members?.length || 0} Members</div>
        </div>
      </section>

      {/* Roadmap & Phases */}
      <section className="space-y-3">
        <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700">Roadmap & Phase Execution</h2>
        <div className="space-y-2">
          {context?.roadmap?.phases?.map((phase: any) => (
            <div key={phase.phase_number} className="p-3.5 rounded-lg border border-slate-200 text-xs flex justify-between items-center">
              <div>
                <span className="font-semibold text-slate-800">Phase {phase.phase_number}: {phase.name}</span>
                <p className="text-slate-500 mt-0.5">{phase.objectives.join(', ')}</p>
              </div>
              <span className="font-mono text-blue-600 font-semibold">{phase.duration_weeks} wks</span>
            </div>
          )) || <div className="text-xs text-slate-400 italic">No roadmap phases recorded.</div>}
        </div>
      </section>

      {/* Risks Analysis */}
      <section className="space-y-3">
        <h2 className="text-sm font-bold uppercase tracking-wider text-slate-700 flex items-center gap-2">
          <ShieldAlert size={16} className="text-rose-500" /> Risk Analysis & Mitigation
        </h2>
        <div className="p-4 rounded-xl bg-rose-50/40 border border-rose-100 text-xs space-y-1">
          <div className="font-semibold text-rose-800">Schedule & Timeline Bottlenecks</div>
          <p className="text-slate-600">Ensure high-priority functional requirements are locked before sprint initialization.</p>
        </div>
      </section>
    </div>
  );
}

export default function ReportPreviewPage() {
  return (
    <Suspense fallback={<div className="p-10 text-center text-xs text-slate-400">Loading...</div>}>
      <ReportContent />
    </Suspense>
  );
}