import { Injectable } from '@nitrostack/core';

export interface ReferralPdfData {
  referralId: string;
  generatedDate: string;
  patientName: string;
  patientAge: number;
  patientGender: string;
  patientSummary: string;
  trialTitle: string;
  trialId: string;
  phase: string;
  sponsor: string;
  status: string;
  location: string;
  eligibilityScore: number;
  matchingCriteria: string[];
  exclusionRisks: string[];
  evidenceReports: { reportType: string; reportDate: string; fileName: string }[];
  recommendation: string;
  llmUsed: string;
}

/**
 * Clinical Copilot MCP Server - PDF Generation Service
 *
 * Generates professional, styled PDF referral documents containing Clinical Copilot headers,
 * patient summaries, trial details, AI eligibility assessments, evidence lists, and recommendations.
 */
@Injectable()
export class PdfService {
  /**
   * Generates a valid standard PDF 1.4 Buffer for the referral document
   */
  async generateReferralPdf(data: ReferralPdfData): Promise<Buffer> {
    const lines: string[] = [
      '=========================================================================',
      '                      CLINICAL COPILOT REFERRAL                          ',
      '=========================================================================',
      `Referral ID     : ${data.referralId}`,
      `Generated Date  : ${data.generatedDate}`,
      `LLM Engine      : ${data.llmUsed}`,
      '-------------------------------------------------------------------------',
      '',
      '1. PATIENT SUMMARY',
      `Patient Name    : ${data.patientName}`,
      `Demographics    : ${data.patientAge} Y / ${data.patientGender}`,
      `Clinical Note   :`,
      ...this.wrapText(data.patientSummary, 70),
      '',
      '2. CLINICAL TRIAL SUMMARY',
      `Trial Title     : ${data.trialTitle}`,
      `NCT Identifier  : ${data.trialId}`,
      `Phase           : ${data.phase}`,
      `Sponsor         : ${data.sponsor}`,
      `Status          : ${data.status}`,
      `Primary Location: ${data.location}`,
      '',
      '3. AI ELIGIBILITY ASSESSMENT',
      `Eligibility Score: ${data.eligibilityScore}%`,
      'Matching Criteria :',
      ...data.matchingCriteria.map((c) => `  * ${c}`),
      'Exclusion Risks   :',
      ...data.exclusionRisks.map((r) => `  * ${r}`),
      '',
      '4. EVIDENCE USED (PROCESSED MEDICAL REPORTS)',
      ...(data.evidenceReports.length > 0
        ? data.evidenceReports.map((e) => `  - [${e.reportDate}] ${e.reportType} (${e.fileName})`)
        : ['  - Initial Clinical Profile Entry']),
      '',
      '5. AI RECOMMENDATION',
      ...this.wrapText(data.recommendation, 70),
      '',
      '=========================================================================',
      '  Generated by Clinical Copilot MCP Server - Confidential Medical Document',
      '=========================================================================',
    ];

    const fullText = lines.join('\n');
    return this.createPdfBuffer(fullText);
  }

  /**
   * Constructs a standard binary PDF 1.4 stream buffer containing styled content
   */
  private createPdfBuffer(textContent: string): Buffer {
    const safeText = textContent
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)');

    const textLines = safeText.split('\n');

    let streamBody = 'BT /F1 9 Tf 12 TL 40 760 Td\n';
    for (const line of textLines) {
      streamBody += `(${line}) '\n`;
    }
    streamBody += 'ET\n';

    const streamLength = Buffer.byteLength(streamBody);

    const pdfObjects = [
      '%PDF-1.4\n%âãÏÓ\n',
      '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
      '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
      '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n',
      `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamBody}endstream\nendobj\n`,
      '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n',
    ];

    let offset = 0;
    const xrefOffsets: number[] = [0];

    let bodyString = '';
    for (const obj of pdfObjects) {
      if (obj.startsWith('%PDF')) {
        offset += Buffer.byteLength(obj);
        bodyString += obj;
      } else {
        xrefOffsets.push(offset);
        offset += Buffer.byteLength(obj);
        bodyString += obj;
      }
    }

    const startXref = offset;
    let xrefString = `xref\n0 ${xrefOffsets.length}\n0000000000 65535 f \n`;
    for (let i = 1; i < xrefOffsets.length; i++) {
      xrefString += `${String(xrefOffsets[i]).padStart(10, '0')} 00000 n \n`;
    }

    const trailerString = `trailer\n<< /Size ${xrefOffsets.length} /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

    return Buffer.from(bodyString + xrefString + trailerString, 'utf-8');
  }

  private wrapText(text: string, maxWidth: number): string[] {
    if (!text) return ['N/A'];
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
      if ((currentLine + ' ' + word).trim().length > maxWidth) {
        lines.push(currentLine.trim());
        currentLine = word;
      } else {
        currentLine += (currentLine ? ' ' : '') + word;
      }
    }
    if (currentLine) lines.push(currentLine.trim());
    return lines;
  }
}
