export const ORCHESTRATOR_EVENTS = {
  MACHINE_ALERT_CREATED: 'machine.alert.created', PURCHASE_APPROVED: 'purchase.approved',
  PURCHASE_REJECTED: 'purchase.rejected', RECOVERY_COMPLETED: 'workflow.recovery.completed',
} as const;

export const ORCHESTRATOR_JOBS = {
  RUN_MAINTENANCE: 'RUN_MAINTENANCE', RUN_INVENTORY: 'RUN_INVENTORY', RUN_PURCHASE: 'RUN_PURCHASE',
  RUN_PRODUCTION_PLANNING: 'RUN_PRODUCTION_PLANNING', RUN_MANAGER: 'RUN_MANAGER', RUN_NOTIFICATION: 'RUN_NOTIFICATION',
  START_MONITORING: 'START_MONITORING',
} as const;
