import { PromptDecorator as Prompt, ExecutionContext } from '@nitrostack/core';

// ---------------------------------------------------------------------------
// EmergencyPrompts — Agent 3: caregiver_briefing MCP Prompt
// ---------------------------------------------------------------------------

export class EmergencyPrompts {

  @Prompt({
    name: 'caregiver_briefing',
    description:
      'Generates a structured weekly caregiver briefing for a family member. Synthesizes health score trends, medication safety flags, counterfeit alerts, genetic risk summaries, and upcoming care tasks into a comprehensive briefing for the primary caregiver.',
    arguments: [
      {
        name: 'patient_id',
        description: 'Patient ID to generate the briefing for (P001, P002, P003). If omitted, generates a summary for all family members.',
        required: false
      },
      {
        name: 'week_of',
        description: 'ISO date string for the week being briefed (e.g., "2024-11-04"). Defaults to current week.',
        required: false
      }
    ]
  })
  async caregiverBriefing(args: { patient_id?: string; week_of?: string }, ctx: ExecutionContext) {
    ctx.logger.info('Generating caregiver briefing prompt', {
      patient_id: args.patient_id,
      week_of: args.week_of
    });

    const weekOf = args.week_of || new Date().toISOString().split('T')[0];
    const patientScope = args.patient_id
      ? `patient ${args.patient_id}`
      : 'all family members (P001 — Arthur, P002 — Mary, P003 — Priya)';

    const systemContext = `You are a compassionate and knowledgeable AI health assistant helping a family caregiver manage the healthcare of a multi-generational household. You have access to the following MCP tools and resources:

**Available Tools:**
- \`check_drug_safety(medication, patient_id)\` — Check gene-drug conflicts and interactions
- \`lookup_drug_label(drug_name)\` — Retrieve FDA-approved drug label warnings
- \`verify_medication_authenticity(drug_name, ndc_code?, batch_number?)\` — Verify medication registry status
- \`extract_health_data(report_text, patient_id?)\` — Parse lab report text into structured entries
- \`update_health_memory(patient_id, entries)\` — Persist extracted lab results into a patient's health profile
- \`generate_emergency_card(patient_id)\` — Generate critical care summary

**Available Resources:**
- \`health://patient-profiles\` — Full family health profiles
- \`health://patient-profile/{patient_id}\` — Individual patient data
- \`medication://pharmacogenomics\` — Gene-drug conflict database
- \`medication://counterfeit-batches\` — Reported counterfeit batch registry

When generating a briefing, you MUST:
1. First fetch the patient profile(s) from the health resources
2. For each active medication, invoke check_drug_safety to surface any gene-drug flags
3. For each active medication with an NDC code, invoke verify_medication_authenticity
4. Highlight any HbA1c, INR, eGFR, or other out-of-range lab values from the patient's recent results
5. Summarize upcoming care tasks based on medication schedules and condition monitoring needs
6. Always end with a "When to Seek Immediate Care" section listing red-flag symptoms relevant to the patient's conditions`;

    const userQuery = `Please generate my weekly caregiver briefing for the week of ${weekOf}, covering ${patientScope}.

Structure the briefing as follows for each family member:

## 👤 [Patient Name] — Weekly Health Briefing

### 📊 Health Status Overview
- Current conditions and stability status
- Recent lab values and trends (flag any out-of-range results)
- Overall health score: 🟢 Stable / 🟡 Monitor / 🔴 Attention Required

### 💊 Medication Safety Review
- List all active medications
- Run check_drug_safety for each medication against patient's genetic profile
- Run verify_medication_authenticity for key medications
- Flag any gene-drug conflicts or authenticity concerns

### 🧬 Genetic Risk Summary
- Active genetic markers and their clinical significance
- Any newly relevant gene-drug interactions to watch

### ✅ Upcoming Care Tasks
- Scheduled lab tests or monitoring (e.g., INR check, HbA1c, thyroid panel)
- Medication refills needed
- Physician follow-up appointments recommended

### 🚨 When to Seek Immediate Care
- Red-flag symptoms specific to this patient's conditions
- Emergency contacts to call`;

    const assistantTemplate = `I'll now generate your comprehensive weekly briefing by accessing the patient profiles and running the necessary safety checks. Please allow a moment while I gather and analyze the data.

---

## Family MedCare — Weekly Caregiver Briefing
**Week of:** ${weekOf}
**Generated by:** Family MedCare Ecosystem — Health Memory & Medication Safety Agents

*[Fetching patient profiles from health://patient-profiles...]*
*[Running medication safety checks...]*
*[Verifying medication authenticity via openFDA...]*

---

I will now provide a full briefing for each family member covering health status, medication safety, genetic risks, care tasks, and emergency guidance.`;

    return [
      {
        role: 'user' as const,
        content: systemContext
      },
      {
        role: 'assistant' as const,
        content: 'Understood. I am now configured as the Family MedCare health assistant with access to all patient health data, medication safety tools, and the openFDA registry. I will proactively use these tools to generate thorough, data-driven briefings.'
      },
      {
        role: 'user' as const,
        content: userQuery
      },
      {
        role: 'assistant' as const,
        content: assistantTemplate
      }
    ];
  }
}
