"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Loader2, Leaf, Droplets, Factory, ArrowUpRight, Zap } from "lucide-react"
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts"

interface CarbonMetrics {
  totalCo2Avoided: number
  totalLandfillDiverted: number
  totalWaterSaved: number
  totalEnergySaved: number
  byFactory: { factoryId: string; factoryName: string; co2Avoided: number; landfillDiverted: number }[]
  byWasteCategory: Record<string, { co2: number; volume: number }>
}

const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#8b5cf6', '#ec4899', '#14b8a6']

export default function CarbonPage() {
  const [metrics, setMetrics] = useState<CarbonMetrics | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch("/api/carbon")
      .then(res => {
        if (!res.ok) throw new Error(`API error: ${res.status}`)
        return res.json()
      })
      .then(data => {
        setMetrics(data)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  if (loading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
      </div>
    )
  }

  if (!metrics) {
    return (
      <div className="flex h-[50vh] flex-col items-center justify-center text-zinc-400">
        <Leaf className="h-12 w-12 mb-4 opacity-50" />
        <h2 className="text-xl font-semibold text-zinc-300">No Carbon Data Available</h2>
        <p className="mt-2 text-sm">The API returned empty or malformed data.</p>
      </div>
    )
  }

  const pieData = Object.entries(metrics.byWasteCategory).map(([name, data]) => ({
    name,
    value: data.co2
  }))

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-zinc-100">Carbon & Impact Metrics</h1>
        <p className="text-zinc-400 mt-1">Real-time tracking of environmental benefits generated by the cluster.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-zinc-400 flex items-center">
              <Leaf className="w-4 h-4 mr-2 text-emerald-500" /> CO₂ Avoided
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-zinc-100">{metrics.totalCo2Avoided} Tons</div>
            <p className="text-xs text-emerald-400 mt-1 flex items-center">
              <ArrowUpRight className="w-3 h-3 mr-1" /> +12% from last month
            </p>
          </CardContent>
        </Card>

        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-zinc-400 flex items-center">
              <Factory className="w-4 h-4 mr-2 text-amber-500" /> Landfill Diverted
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-zinc-100">{metrics.totalLandfillDiverted} Tons</div>
            <p className="text-xs text-emerald-400 mt-1 flex items-center">
              <ArrowUpRight className="w-3 h-3 mr-1" /> +5% from last month
            </p>
          </CardContent>
        </Card>

        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-zinc-400 flex items-center">
              <Droplets className="w-4 h-4 mr-2 text-blue-500" /> Water Saved
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-zinc-100">{metrics.totalWaterSaved} L</div>
            <p className="text-xs text-zinc-500 mt-1">Estimated conservation</p>
          </CardContent>
        </Card>
        
        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-zinc-400 flex items-center">
              <Zap className="w-4 h-4 mr-2 text-purple-500" /> Energy Saved
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-zinc-100">{metrics.totalEnergySaved} kWh</div>
            <p className="text-xs text-zinc-500 mt-1">Estimated conservation</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader>
            <CardTitle className="text-base text-zinc-200">CO₂ Avoided by Factory (Top 10)</CardTitle>
            <CardDescription>Measured in tons per year</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={metrics.byFactory.slice(0, 10)} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#27272a" vertical={false} />
                <XAxis dataKey="factoryName" stroke="#52525b" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => value.length > 10 ? value.substring(0, 10) + '...' : value} />
                <YAxis stroke="#52525b" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip 
                  cursor={{fill: '#27272a', opacity: 0.4}} 
                  contentStyle={{ backgroundColor: '#09090b', borderColor: '#27272a', borderRadius: '8px' }} 
                />
                <Bar dataKey="co2Avoided" fill="#10b981" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="bg-zinc-950/50 border-zinc-800 backdrop-blur">
          <CardHeader>
            <CardTitle className="text-base text-zinc-200">CO₂ Avoided by Waste Category</CardTitle>
            <CardDescription>Distribution across material types</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px] flex items-center justify-center">
            {pieData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    paddingAngle={2}
                    dataKey="value"
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip contentStyle={{ backgroundColor: '#09090b', borderColor: '#27272a', borderRadius: '8px' }} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="text-zinc-500 text-sm">No categorical data available</div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
