import test from 'node:test'; import assert from 'node:assert/strict';
process.env.FACTORYBRAIN_WEBSOCKET_ENABLED = 'false'; delete process.env.MONGODB_URI; delete process.env.REDIS_URL;
const { DatabaseService } = await import('../dist/services/database.service.js');
const { QueueService } = await import('../dist/services/queue.service.js');
const { NotificationRealtimeService } = await import('../dist/modules/notification/notification-realtime.service.js');
const { DurationRulesService } = await import('../dist/modules/monitoring/duration-rules.service.js');
const { MockStatusService } = await import('../dist/modules/monitoring/mock-status.service.js');
const { MonitoringAgent } = await import('../dist/modules/monitoring/monitoring.agent.js');
async function setup() { const database = new DatabaseService(); await database.onModuleInit(); const queue = new QueueService(database); await queue.onModuleInit(); const managerStatuses = []; queue.registerHandler('manager', 'workflow_status', async (event) => { managerStatuses.push(event.payload); }); const realtime = new NotificationRealtimeService(database); await realtime.onModuleInit(); const sources = new MockStatusService(); const agent = new MonitoringAgent(database, queue, new DurationRulesService(), sources, realtime); await agent.onModuleInit(); return { database, queue, realtime, sources, agent, managerStatuses }; }
function plan(id = 'WF-1', purchase = true) { const now = new Date().toISOString(); return { workflowId: id, ticketId: `T-${id}`, machineId: 'M7', approvedAt: now, approvedBy: 'Manager Agent', approval: { approvalId: `APR-${id}`, status: 'Approved' }, report: {}, maintenance: {}, ...(purchase ? { purchase: {} } : {}), production: {}, originalRequester: 'Maintenance Agent', notifiedAt: now, notifications: [{ notificationId: `N-${id}`, status: 'Sent' }] }; }
function update(workflowId, eventId, source, status, offset = 0) { return { workflowId, eventId, source, status, occurredAt: new Date(Date.now() + offset).toISOString() }; }

test('tracks a successful notified workflow until the machine returns to service', async () => { const c = await setup(); await c.agent.trackWorkflow(plan());
  c.sources.set(update('WF-1', 'E1', 'procurement', 'supplier accepted')); await c.agent.poll();
  await c.agent.handleStatus(update('WF-1', 'E2', 'procurement', 'part shipped', 1)); await c.agent.handleStatus(update('WF-1', 'E3', 'procurement', 'delivered', 2)); await c.agent.handleStatus(update('WF-1', 'E4', 'maintenance', 'repair started', 3)); await c.agent.handleStatus(update('WF-1', 'E5', 'maintenance', 'completed', 4)); await c.agent.handleStatus(update('WF-1', 'E6', 'machine', 'running', 5));
  const workflow = c.database.findMonitoringWorkflow('WF-1'); assert.equal(workflow.currentStage, 'Completed'); assert.equal(workflow.status, 'Completed'); assert.ok(workflow.completedAt); assert.equal(c.database.listMonitoringEvents('WF-1').length, 9);
  assert.equal(c.managerStatuses.at(-1).state, 'Completed');
  const liveEvents = c.database.listMonitoringLiveEvents(); assert.deepEqual(liveEvents.map((event) => event.sequence), [1, 2, 3, 4, 5, 6, 7, 8, 9]);
  assert.deepEqual(c.realtime.recoverMonitoring(7).map((event) => event.sequence), [8, 9]);
});
test('detects a delayed stage and resolves its alert when progress resumes', async () => { const c = await setup(); const workflow = await c.agent.trackWorkflow(plan('WF-DELAY')); const alert = await c.agent.detectStall('WF-DELAY', new Date(Date.parse(workflow.stageDeadline) + 1)); assert.equal(alert.status, 'Open'); assert.equal(c.database.findMonitoringWorkflow('WF-DELAY').status, 'Delayed'); assert.equal(c.managerStatuses.at(-1).state, 'Delayed'); await c.agent.handleStatus(update('WF-DELAY', 'D1', 'procurement', 'supplier accepted')); assert.equal(c.database.listMonitoringAlerts('WF-DELAY')[0].status, 'Resolved'); assert.equal(c.database.findMonitoringWorkflow('WF-DELAY').status, 'Active'); });
test('marks a workflow failed from an external failure event', async () => { const c = await setup(); await c.agent.trackWorkflow(plan('WF-FAIL')); await c.agent.handleStatus(update('WF-FAIL', 'F1', 'procurement', 'failed')); const workflow = c.database.findMonitoringWorkflow('WF-FAIL'); assert.equal(workflow.currentStage, 'Failed'); assert.equal(workflow.status, 'Failed'); });
test('suppresses duplicate external events', async () => { const c = await setup(); await c.agent.trackWorkflow(plan('WF-DUP')); const event = update('WF-DUP', 'DUP-1', 'procurement', 'supplier accepted'); await c.agent.handleStatus(event); await c.agent.handleStatus(event); assert.equal(c.database.listMonitoringEvents('WF-DUP').filter((item) => item.duplicateKey === 'DUP-1').length, 1); });
test('defers out-of-order events and replays them after prerequisites arrive', async () => { const c = await setup(); await c.agent.trackWorkflow(plan('WF-ORDER')); await c.agent.handleStatus(update('WF-ORDER', 'O4', 'maintenance', 'started', 4)); assert.equal(c.database.findMonitoringWorkflow('WF-ORDER').currentStage, 'Teams Notified'); assert.equal(c.database.findMonitoringWorkflow('WF-ORDER').deferredEvents.length, 1); await c.agent.handleStatus(update('WF-ORDER', 'O1', 'procurement', 'supplier accepted', 1)); await c.agent.handleStatus(update('WF-ORDER', 'O2', 'procurement', 'part shipped', 2)); await c.agent.handleStatus(update('WF-ORDER', 'O3', 'procurement', 'delivered', 3)); const workflow = c.database.findMonitoringWorkflow('WF-ORDER'); assert.equal(workflow.currentStage, 'Repair Started'); assert.equal(workflow.deferredEvents.length, 0); });
