import test from 'node:test'; import assert from 'node:assert/strict'; import { dirname, resolve } from 'node:path'; import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
process.env.FACTORYBRAIN_WEBSOCKET_ENABLED = 'false'; process.env.FACTORYBRAIN_APPROVAL_THRESHOLD = '100000'; process.env.FACTORYBRAIN_INVENTORY_CSV = resolve(root, 'tests/fixtures/inventory_e2e_out_of_stock.csv'); process.env.FACTORYBRAIN_SUPPLIERS_CSV = resolve(root, 'tests/fixtures/suppliers_sample.csv'); process.env.FACTORYBRAIN_PURCHASE_REQUESTS_CSV = resolve(root, 'tests/fixtures/purchase_requests_sample.csv'); delete process.env.MONGODB_URI; delete process.env.REDIS_URL;
test('Machine -> Maintenance -> Inventory -> Purchase -> Production -> Manager -> Notification -> Monitoring -> Running', async () => {
  const [{ DatabaseService }, { QueueService }, { MachineAgent }, { MaintenanceAgent }, { InventoryCsvService }, { InventoryAgent }, { SupplierService }, { ScoringService }, { PurchaseRequestService }, { PurchaseAgent }, { ProductionDataService }, { ProductionAgent }, { FactoryConfigService }, { ManagerAgent }, { RecipientConfigService }, { MessageTemplateService }, { NotificationDeliveryService }, { NotificationRealtimeService }, { NotificationAgent }, { DurationRulesService }, { MockStatusService }, { MonitoringAgent }, { OrchestratorService }, { OrchestratorProcessor }, { WorkflowStateService }] = await Promise.all([
    import('../dist/services/database.service.js'), import('../dist/services/queue.service.js'), import('../dist/modules/machine/machine.agent.js'), import('../dist/modules/maintenance/maintenance.agent.js'), import('../dist/modules/inventory/inventory-csv.service.js'), import('../dist/modules/inventory/inventory.agent.js'), import('../dist/modules/purchase/supplier.service.js'), import('../dist/modules/purchase/scoring.service.js'), import('../dist/modules/purchase/purchase-request.service.js'), import('../dist/modules/purchase/purchase.agent.js'), import('../dist/modules/production/production-data.service.js'), import('../dist/modules/production/production.agent.js'), import('../dist/modules/manager/factory-config.service.js'), import('../dist/modules/manager/manager.agent.js'), import('../dist/modules/notification/recipient-config.service.js'), import('../dist/modules/notification/message-template.service.js'), import('../dist/modules/notification/notification-delivery.service.js'), import('../dist/modules/notification/notification-realtime.service.js'), import('../dist/modules/notification/notification.agent.js'), import('../dist/modules/monitoring/duration-rules.service.js'), import('../dist/modules/monitoring/mock-status.service.js'), import('../dist/modules/monitoring/monitoring.agent.js'), import('../dist/orchestrator/orchestrator.service.js'), import('../dist/orchestrator/orchestrator.processor.js'), import('../dist/orchestrator/workflow-state.service.js'),
  ]);
  const database = new DatabaseService(); const queue = new QueueService(database); const inventoryStore = new InventoryCsvService(database); const suppliers = new SupplierService(); const purchaseRequests = new PurchaseRequestService(database); const productionData = new ProductionDataService(database); const realtime = new NotificationRealtimeService(database);
  const maintenance = new MaintenanceAgent(database, queue); const inventory = new InventoryAgent(inventoryStore, queue); const purchase = new PurchaseAgent(suppliers, new ScoringService(), purchaseRequests, queue); const production = new ProductionAgent(database, productionData, queue); const manager = new ManagerAgent(database, new FactoryConfigService(database), queue); const notification = new NotificationAgent(database, queue, new RecipientConfigService(), new MessageTemplateService(), new NotificationDeliveryService(), realtime); const monitoring = new MonitoringAgent(database, queue, new DurationRulesService(), new MockStatusService(), realtime); const workflowState = new WorkflowStateService(database); const processor = new OrchestratorProcessor(database, queue, workflowState); const orchestrator = new OrchestratorService(queue, workflowState, manager); const machine = new MachineAgent(database, queue);
  try {
    await database.onModuleInit(); await queue.onModuleInit(); await inventoryStore.onModuleInit(); await suppliers.onModuleInit(); await purchaseRequests.onModuleInit(); await productionData.onModuleInit(); await maintenance.onModuleInit(); await inventory.onModuleInit(); await purchase.onModuleInit(); await production.onModuleInit(); await manager.onModuleInit(); await realtime.onModuleInit(); await notification.onModuleInit(); await monitoring.onModuleInit(); await workflowState.onModuleInit(); await processor.onModuleInit(); await orchestrator.onModuleInit();
    for (let index = 0; index < 3; index += 1) await machine.analyzeReading(extremeReading(`2026-07-26T08:0${index}:00.000Z`));
    const workflow = manager.listWorkflows()[0]; assert.ok(workflow); assert.equal(workflow.state, 'Monitoring Active');
    const request = database.listPurchaseRequests().find((item) => item.partName === 'Bearing X45' && item.purchaseRequestId !== 'PR001'); assert.ok(request); assert.equal(request.approvalStatus, 'Approved'); assert.equal(request.purchaseStatus, 'Ordered'); assert.ok(request.approvedBy);
    const notifications = database.listNotifications({ workflowId: workflow.workflowId }); assert.equal(notifications.length, 5); assert.equal(notifications.every((item) => item.status === 'Sent'), true); assert.equal(database.findMonitoringWorkflow(workflow.workflowId).currentStage, 'Teams Notified');
    const updates = [['procurement', 'supplier accepted'], ['procurement', 'part shipped'], ['procurement', 'delivered'], ['maintenance', 'repair started'], ['maintenance', 'completed']];
    for (let index = 0; index < updates.length; index += 1) await queue.publish({ from: 'e2e', to: 'monitoring', type: 'status_update', payload: { eventId: `E2E-${index}`, workflowId: workflow.workflowId, source: updates[index][0], status: updates[index][1], occurredAt: new Date(Date.now() + index).toISOString() } });
    const factoryWorkflow = workflowState.list()[0]; assert.equal(factoryWorkflow.status, 'MONITORING'); await queue.publish({ from: 'machine', to: 'orchestrator', type: 'workflow.recovery.completed', payload: { workflowId: factoryWorkflow.workflowId, machineId: factoryWorkflow.machineId, machineStatus: 'Operational', actualDowntimeHours: 7.5, actualDowntimeLoss: 37500, completedAt: new Date().toISOString() } }, { idempotencyKey: `${factoryWorkflow.workflowId}:recovery-event` });
    const completed = database.findMonitoringWorkflow(workflow.workflowId); assert.equal(completed.currentStage, 'Completed'); assert.equal(completed.status, 'Completed'); assert.ok(completed.completedAt); assert.equal(manager.listWorkflows()[0].state, 'Completed'); assert.deepEqual(completed.history.map((item) => item.stage), ['Purchase Approved', 'Teams Notified', 'Supplier Accepted', 'Part Shipped', 'Part Delivered', 'Repair Started', 'Machine Validation', 'Machine Running', 'Completed']); assert.equal(database.listMonitoringEvents(workflow.workflowId).length, 9); assert.equal(workflowState.list()[0].status, 'COMPLETED'); assert.equal(workflowState.list()[0].currentStage, 'COMPLETED'); assert.equal(database.listWorkflowAgentEvents(factoryWorkflow.workflowId).some((event) => event.eventType === 'WORKFLOW_COMPLETED'), true); const events = database.listAgentEvents(); assert.equal(events.filter((event) => event.status === 'delivered').length > 10, true);
    if (process.env.FACTORYBRAIN_PRINT_SIMULATION === 'true') console.log('SIMULATION_RESULT=' + JSON.stringify({ readings: database.getRecentReadings(process.env.FACTORYBRAIN_SIM_MACHINE ?? 'M002', 3), alerts: database.listAlerts(process.env.FACTORYBRAIN_SIM_MACHINE ?? 'M002'), tickets: database.listMaintenanceTickets(process.env.FACTORYBRAIN_SIM_MACHINE ?? 'M002'), inventory: inventoryStore.listItems().find((item) => item.partName === 'Bearing X45'), purchaseRequest: request, managerWorkflow: manager.listWorkflows()[0], monitoring: completed, factoryWorkflow: workflowState.list()[0], notifications }, null, 2));
  } finally { await realtime.close(); await queue.close(); await database.close(); }
});
function extremeReading(timestamp) { return { machineId: process.env.FACTORYBRAIN_SIM_MACHINE ?? 'M002', timestamp, airTemperature: 450, processTemperature: 500, rpm: 4000, torque: 150, vibration: 5, pressure: 20, humidity: 95, voltage: 400, current: 100, powerConsumption: 50, toolWear: 500, operatingHours: 50000 }; }
