import { Injectable } from '@nitrostack/core';
import type { ShoeRecord } from '../types/shoe.types.js';

export interface DecathlonSportsShoe extends ShoeRecord {
  sport: string;
  cushioning_technology: string;
  drop_mm: number;
  weight_g: number;
}

@Injectable()
export class DecathlonSportsApiService {
  private decathlonCatalog: DecathlonSportsShoe[] = [
    {
      id: 'decathlon-kiprun-ks900-2',
      brand: 'Decathlon Kiprun',
      model: 'Kiprun KS900 2 Max Cushion',
      gender: 'unisex',
      size_us: 9.5,
      size_uk: 8.5,
      size_eu: 42.5,
      length_mm: 270,
      width_mm: 101,
      ratio: 2.67,
      width_category: 'standard',
      category: 'Sports',
      sport: 'Road Running',
      cushioning_technology: 'Mousse M-Foam Cushioning',
      drop_mm: 8,
      weight_g: 275,
      heel_counter: 'Firm',
      cushioning: 'Maximum',
      standing_rating: 10,
      price_usd: 105,
      price_inr: 8999,
      url: 'https://www.decathlon.in/p/8786524/running-shoes/men-running-shoes-kiprun-ks900-2',
      image_url: 'https://contents.mediadecathlon.com/p2472937/k$a4c6a6f1d2d5351a02102143b8a92f80/men-running-shoes-kiprun-ks900-2-blue.jpg?format=auto&quality=70&f=650x650',
      source: 'decathlon_api',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'decathlon-kiprun-fast-2',
      brand: 'Decathlon Kiprun',
      model: 'Kiprun Fast 2 Tempo',
      gender: 'unisex',
      size_us: 9.5,
      size_uk: 8.5,
      size_eu: 42.5,
      length_mm: 270,
      width_mm: 100,
      ratio: 2.7,
      width_category: 'standard',
      category: 'Sports',
      sport: 'Speed & Interval Running',
      cushioning_technology: 'K-Ring + Kalensole Foam',
      drop_mm: 6,
      weight_g: 245,
      heel_counter: 'Medium',
      cushioning: 'High',
      standing_rating: 9,
      price_usd: 75,
      price_inr: 5999,
      url: 'https://www.decathlon.in/p/8559090/running-shoes/men-running-shoes-kiprun-fast-2',
      image_url: 'https://contents.mediadecathlon.com/p2153542/k$13247072f88cf7c897f1f4142f1f5012/men-running-shoes-kiprun-fast-2.jpg?format=auto&quality=70&f=650x650',
      source: 'decathlon_api',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'decathlon-kalenji-run-cushion',
      brand: 'Decathlon Kalenji',
      model: 'Kalenji Run Cushion',
      gender: 'unisex',
      size_us: 9.5,
      size_uk: 8.5,
      size_eu: 42.5,
      length_mm: 270,
      width_mm: 100,
      ratio: 2.7,
      width_category: 'standard',
      category: 'Sports',
      sport: 'Daily Jogging',
      cushioning_technology: 'EVA Cushioning Sole',
      drop_mm: 10,
      weight_g: 235,
      heel_counter: 'Medium',
      cushioning: 'Medium',
      standing_rating: 8,
      price_usd: 25,
      price_inr: 1999,
      url: 'https://www.decathlon.in/p/8559085/running-shoes/kalenji-run-cushion-shoes',
      image_url: 'https://contents.mediadecathlon.com/p1816350/k$e868a252277d34190c1f6c77d6118b82/men-running-shoes-run-cushion-black.jpg?format=auto&quality=70&f=650x650',
      source: 'decathlon_api',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'decathlon-evadict-mt-cushion-2',
      brand: 'Decathlon Evadict',
      model: 'Evadict MT Cushion 2 Trail',
      gender: 'unisex',
      size_us: 9.5,
      size_uk: 8.5,
      size_eu: 42.5,
      length_mm: 270,
      width_mm: 102,
      ratio: 2.65,
      width_category: 'standard',
      category: 'Sports',
      sport: 'Trail Running & Outdoor',
      cushioning_technology: 'Kalensole + MATRYX Mesh Upper',
      drop_mm: 4,
      weight_g: 295,
      heel_counter: 'Firm',
      cushioning: 'High',
      standing_rating: 9,
      price_usd: 95,
      price_inr: 7999,
      url: 'https://www.decathlon.in/p/8786529/trail-running/men-trail-running-shoes-evadict-mt-cushion-2',
      image_url: 'https://contents.mediadecathlon.com/p2384720/k$98442a2298c56d782782b52825b74102/men-trail-running-shoes-mt-cushion-2.jpg?format=auto&quality=70&f=650x650',
      source: 'decathlon_api',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'decathlon-artengo-ts960',
      brand: 'Decathlon Artengo',
      model: 'Artengo TS960 Pro Tennis',
      gender: 'unisex',
      size_us: 9.5,
      size_uk: 8.5,
      size_eu: 42.5,
      length_mm: 270,
      width_mm: 101,
      ratio: 2.67,
      width_category: 'standard',
      category: 'Sports',
      sport: 'Tennis / Court',
      cushioning_technology: 'Lateral CS System + RUUBR Outsole',
      drop_mm: 8,
      weight_g: 340,
      heel_counter: 'Firm',
      cushioning: 'High',
      standing_rating: 9,
      price_usd: 65,
      price_inr: 5499,
      url: 'https://www.decathlon.in/p/8559092/tennis-shoes/artengo-ts960-tennis-shoes',
      image_url: 'https://contents.mediadecathlon.com/p2012480/k$6a782b52825b74102c5253818312019a/artengo-ts960-tennis-shoes.jpg?format=auto&quality=70&f=650x650',
      source: 'decathlon_api',
      last_updated: new Date().toISOString(),
    },
  ];

  getDecathlonSportsShoes(): DecathlonSportsShoe[] {
    return this.decathlonCatalog;
  }
}
