/**
 * Generates two demo-facing artifacts from detection output:
 *   - exportReconstructedSpec: an OpenAPI 3.0 document describing the API as
 *     it actually behaves in production, not as it was declared.
 *   - generateAuthzTestSuite: a regression test for the OWNING team's own CI,
 *     never a live exploit against a host we don't control.
 *
 * Deviation from the build spec worth flagging: exportReconstructedSpec's
 * given signature is (templates, findings), but "integer for NUMERIC,
 * string+uuid for UUID" schema inference needs a sample concrete value per
 * param position — EndpointTemplate/PathParam (locked exactly by types.ts)
 * carry none. This takes `records` as a third parameter so the inference is
 * real rather than guessed from the param name.
 */

import type { AccessLogRecord, EndpointTemplate, Finding } from './types.js';
import { templatisePaths } from './templatise.js';

const NUMERIC = /^\d+$/;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

interface ParamSchema {
  type: 'integer' | 'string';
  format?: 'uuid';
}

function inferSchema(sampleValue: string | undefined): ParamSchema {
  if (sampleValue !== undefined && NUMERIC.test(sampleValue)) return { type: 'integer' };
  if (sampleValue !== undefined && UUID.test(sampleValue)) return { type: 'string', format: 'uuid' };
  return { type: 'string' };
}

const STATUS_DESCRIPTIONS: Record<string, string> = {
  '200': 'OK',
  '201': 'Created',
  '204': 'No Content',
  '400': 'Bad Request',
  '401': 'Unauthorized',
  '403': 'Forbidden',
  '404': 'Not Found',
  '429': 'Too Many Requests',
  '500': 'Internal Server Error',
};

function describeStatus(status: string): string {
  return STATUS_DESCRIPTIONS[status] ?? 'Response';
}

export function exportReconstructedSpec(
  templates: EndpointTemplate[],
  findings: Finding[],
  records: AccessLogRecord[],
): object {
  const templateMap = templatisePaths(records.map((r) => r.path));
  const recordsByTemplate = new Map<string, AccessLogRecord[]>();
  for (const r of records) {
    const t = templateMap.get(r.path);
    if (t === undefined) continue;
    if (!recordsByTemplate.has(t)) recordsByTemplate.set(t, []);
    recordsByTemplate.get(t)!.push(r);
  }

  const findingsByTemplate = new Map<string, Finding[]>();
  for (const f of findings) {
    if (!findingsByTemplate.has(f.template)) findingsByTemplate.set(f.template, []);
    findingsByTemplate.get(f.template)!.push(f);
  }

  const sortedTemplates = [...templates].sort((a, b) => a.template.localeCompare(b.template));
  const paths: Record<string, Record<string, unknown>> = {};

  for (const t of sortedTemplates) {
    const recs = recordsByTemplate.get(t.template) ?? [];
    const operations: Record<string, unknown> = {};

    for (const method of [...t.methods].sort()) {
      const parameters = t.params.map((p) => {
        const sample = recs
          .map((r) => r.path.split('/').filter((s) => s.length > 0)[p.position])
          .find((v) => v !== undefined);
        return { name: p.name, in: 'path', required: true, schema: inferSchema(sample) };
      });

      const responses: Record<string, { description: string }> = {};
      for (const status of Object.keys(t.statusCounts).sort()) {
        responses[status] = { description: describeStatus(status) };
      }

      const templateFindings = [...(findingsByTemplate.get(t.template) ?? [])].sort((a, b) => a.id.localeCompare(b.id));

      operations[method.toLowerCase()] = {
        summary: `${method} ${t.template}`,
        parameters,
        responses,
        'x-domainexpansion': {
          observedRequestCount: t.requestCount,
          distinctActors: t.distinctActors,
          firstSeen: t.firstSeen,
          lastSeen: t.lastSeen,
          documented: t.documented,
          findingIds: templateFindings.map((f) => f.id),
          evidenceUris: templateFindings.map((f) => f.evidenceUri),
        },
      };
    }

    paths[t.template] = operations;
  }

  return {
    openapi: '3.0.0',
    info: { title: 'DomainExpansion Reconstructed API', version: '1.0.0' },
    paths,
  };
}

function extractParamPlaceholder(template: string): string {
  const match = template.match(/\{[^}]+\}/);
  return match ? match[0] : '{id}';
}

function generateJestSuite(finding: Finding): { filename: string; source: string } {
  const filename = `authz.${finding.id}.test.ts`;
  const method = finding.methods[0] ?? 'GET';
  const paramPlaceholder = extractParamPlaceholder(finding.template);

  const lines = [
    '/**',
    ' * Authorization regression test — generated by DomainExpansion.ai',
    ' *',
    ` * Finding:  ${finding.id} (${finding.rule})`,
    ` * CWE:      ${finding.cwe} — ${finding.cweTitle}`,
    ` * Evidence: ${finding.evidenceUri}`,
    ' *',
    ' * TODO: set AUTHZ_TEST_BASE_URL and the two principals\' auth tokens for',
    ' * YOUR OWN service below, as environment variables in your CI\'s secret',
    ' * store. Never commit real credentials into this file.',
    ' */',
    "import { describe, it, expect } from '@jest/globals';",
    '',
    "const BASE_URL = process.env.AUTHZ_TEST_BASE_URL ?? 'https://TODO-set-your-own-service-url';",
    '// TODO: token for the principal who OWNS the target object',
    'const PRINCIPAL_A_TOKEN = process.env.AUTHZ_TEST_PRINCIPAL_A_TOKEN;',
    '// TODO: token for a principal who must NOT be able to access it',
    'const PRINCIPAL_B_TOKEN = process.env.AUTHZ_TEST_PRINCIPAL_B_TOKEN;',
    '// TODO: substitute a real object ID owned by principal A',
    `const TARGET_PATH = '${finding.template}'.replace('${paramPlaceholder}', 'REPLACE_WITH_PRINCIPAL_A_OBJECT_ID');`,
    '',
    `describe('${finding.rule} regression — ${finding.template}', () => {`,
    "  it('denies principal B access to an object owned by principal A', async () => {",
    '    if (!PRINCIPAL_A_TOKEN || !PRINCIPAL_B_TOKEN) {',
    "      throw new Error('Set AUTHZ_TEST_PRINCIPAL_A_TOKEN and AUTHZ_TEST_PRINCIPAL_B_TOKEN before running this test.');",
    '    }',
    '    const response = await fetch(`${BASE_URL}${TARGET_PATH}`, {',
    `      method: '${method}',`,
    '      headers: { Authorization: `Bearer ${PRINCIPAL_B_TOKEN}` },',
    '    });',
    '    expect([403, 404]).toContain(response.status);',
    '    expect(response.status).not.toBe(200);',
    '  });',
    '});',
    '',
  ];

  return { filename, source: lines.join('\n') };
}

function generatePytestSuite(finding: Finding): { filename: string; source: string } {
  const filename = `test_authz_${finding.id}.py`;
  const method = finding.methods[0] ?? 'GET';
  const paramPlaceholder = extractParamPlaceholder(finding.template);
  const testFnName = `test_${finding.rule.toLowerCase()}_denies_cross_principal_access`;

  const lines = [
    '"""',
    'Authorization regression test — generated by DomainExpansion.ai',
    '',
    `Finding:  ${finding.id} (${finding.rule})`,
    `CWE:      ${finding.cwe} — ${finding.cweTitle}`,
    `Evidence: ${finding.evidenceUri}`,
    '',
    "TODO: set AUTHZ_TEST_BASE_URL and the two principals' auth tokens for YOUR",
    'OWN service as environment variables before running. Never commit real',
    'credentials into this file.',
    '"""',
    'import os',
    'import requests',
    '',
    'BASE_URL = os.environ.get("AUTHZ_TEST_BASE_URL", "https://TODO-set-your-own-service-url")',
    '# TODO: token for the principal who OWNS the target object',
    'PRINCIPAL_A_TOKEN = os.environ.get("AUTHZ_TEST_PRINCIPAL_A_TOKEN")',
    '# TODO: token for a principal who must NOT be able to access it',
    'PRINCIPAL_B_TOKEN = os.environ.get("AUTHZ_TEST_PRINCIPAL_B_TOKEN")',
    '# TODO: substitute a real object ID owned by principal A',
    `TARGET_PATH = "${finding.template}".replace("${paramPlaceholder}", "REPLACE_WITH_PRINCIPAL_A_OBJECT_ID")`,
    '',
    '',
    `def ${testFnName}():`,
    '    assert PRINCIPAL_A_TOKEN and PRINCIPAL_B_TOKEN, (',
    '        "Set AUTHZ_TEST_PRINCIPAL_A_TOKEN and AUTHZ_TEST_PRINCIPAL_B_TOKEN"',
    '    )',
    `    response = requests.request("${method}", BASE_URL + TARGET_PATH, headers={`,
    '        "Authorization": f"Bearer {PRINCIPAL_B_TOKEN}",',
    '    })',
    '    assert response.status_code in (403, 404)',
    '',
  ];

  return { filename, source: lines.join('\n') };
}

export function generateAuthzTestSuite(
  finding: Finding,
  framework: 'jest' | 'pytest',
): { filename: string; source: string } {
  return framework === 'jest' ? generateJestSuite(finding) : generatePytestSuite(finding);
}
