import { PlatformType } from '../shared/enums/platform.enum';
import { PriorityLevel } from '../shared/enums/priority.enum';
import { MessageStatus } from '../shared/enums/message.enum';
import { TaskStatus } from '../shared/enums/task.enum';
import { NotificationType } from '../shared/enums/notification.enum';
import { AgentType } from '../shared/enums/agent.enum';
import { Message } from '../shared/interfaces/Message.interface';
import { Task } from '../shared/interfaces/Task.interface';
import { CalendarEvent } from '../shared/interfaces/CalendarEvent.interface';
import { Notification } from '../shared/interfaces/Notification.interface';


export interface AgentExecutionLog {
  id: string;
  agent: AgentType;
  agentName: string;
  action: string;
  details: string;
  timestamp: string;
  durationMs: number;
  status: 'completed' | 'in_progress' | 'pending' | 'failed';
  mcpTool?: string;
}

export interface PlatformConnection {
  platform: PlatformType;
  name: string;
  status: 'connected' | 'syncing' | 'disconnected';
  lastSync: string;
  account: string;
  activeCount: number;
  icon: string;
}

export const MOCK_PLATFORM_CONNECTIONS: PlatformConnection[] = [
  { platform: PlatformType.GMAIL, name: 'Gmail Workspace', status: 'connected', lastSync: '1 min ago', account: 'alex.mercer@converra.io', activeCount: 14, icon: '✉️' },
  { platform: PlatformType.SLACK, name: 'Slack HQ', status: 'connected', lastSync: 'Just now', account: '#engineering-core', activeCount: 28, icon: '💬' },
  { platform: PlatformType.DISCORD, name: 'Discord Devs', status: 'connected', lastSync: '3 mins ago', account: 'AlexM#4920', activeCount: 8, icon: '🎮' },
  { platform: PlatformType.GITHUB, name: 'GitHub Enterprise', status: 'connected', lastSync: '12 mins ago', account: 'converra-labs', activeCount: 19, icon: '🐙' },
  { platform: PlatformType.NOTION, name: 'Notion Workspace', status: 'connected', lastSync: '5 mins ago', account: 'Engineering Hub', activeCount: 6, icon: '📝' },
  { platform: PlatformType.CALENDAR, name: 'Google Calendar', status: 'connected', lastSync: 'Just now', account: 'alex.mercer@converra.io', activeCount: 4, icon: '📅' },
];

export const MOCK_MESSAGES: Message[] = [
  // --- UNREAD (14 Messages) ---
  {
    id: 'msg-101',
    conversationId: 'conv-01',
    platform: PlatformType.GMAIL,
    externalId: 'gm-88491',
    sender: { id: 'usr-prof', name: 'Dr. Evelyn Vance', email: 'e.vance@stanford.edu', avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'URGENT: Review CS340 Final Project Architecture Blueprint',
    content: 'Hi Alex, regarding the distributed system blueprint you submitted for the final project: we need to adjust the raft consensus layer timeout parameters before Monday morning review. Could you review section 4.2 and let me know if we can schedule a quick 15-minute call today at 3:00 PM?',
    timestamp: new Date('2026-07-25T09:15:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.URGENT,
    tags: ['Academic', 'Engineering', 'Architecture', 'Urgent Call'],
  },
  {
    id: 'msg-102',
    conversationId: 'conv-02',
    platform: PlatformType.SLACK,
    externalId: 'slk-99120',
    sender: { id: 'usr-devlead', name: 'Sarah Chen (Lead Architect)', email: 'sarah.chen@converra.io', avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'NitroStack Core v1.4 Deployment Blockers',
    content: '@alex The release candidate for NitroStack v1.4 hit a memory leak on worker node 3 during stress testing. We need your insight on the garbage collection parameters in the memory module before approving PR #342.',
    timestamp: new Date('2026-07-25T10:02:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.HIGH,
    tags: ['Engineering', 'Release', 'Memory Leak', 'PR Review'],
  },
  {
    id: 'msg-104',
    conversationId: 'conv-04',
    platform: PlatformType.DISCORD,
    externalId: 'dsc-10928',
    sender: { id: 'usr-designer', name: 'Marcus Brody (UX Design)', avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Figma Token Sync for Converra One Glassmorphism Theme',
    content: 'Hey Alex! I just updated the Figma design tokens for dark glassmorphism gradients and card border highlights. Take a look at the `#design-system` channel when you get a second.',
    timestamp: new Date('2026-07-25T11:20:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Design System', 'UI/UX', 'Figma'],
  },
  {
    id: 'msg-106',
    conversationId: 'conv-06',
    platform: PlatformType.GMAIL,
    externalId: 'gm-99182',
    sender: { id: 'usr-sec', name: 'CloudSec Security Alert Bot', email: 'security-alerts@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'CRITICAL SECURITY ALERT: Outdated Dependency Flagged in Docker Base Image',
    content: 'CVE-2026-4419 detected in alpine:3.18 base layer image. Immediate patch required for node-worker pod deployments.',
    timestamp: new Date('2026-07-25T12:10:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.URGENT,
    tags: ['Engineering', 'Security Alert', 'Docker'],
  },
  {
    id: 'msg-107',
    conversationId: 'conv-07',
    platform: PlatformType.SLACK,
    externalId: 'slk-11029',
    sender: { id: 'usr-jira', name: 'Jira Integration Bot', email: 'jira-notifications@converra.atlassian.net' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[JIRA-891] Issue Assigned: Optimize MCP Stdio Pipe Latency',
    content: 'Ticket CON-891 "Optimize MCP Stdio Pipe Latency under multi-agent concurrent dispatch" assigned to Alex Mercer with Priority HIGH.',
    timestamp: new Date('2026-07-25T13:00:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.HIGH,
    tags: ['Jira', 'Engineering', 'MCP'],
  },
  {
    id: 'msg-108',
    conversationId: 'conv-08',
    platform: PlatformType.GMAIL,
    externalId: 'gm-77123',
    sender: { id: 'usr-hr', name: 'Jessica Miller (HR People Ops)', email: 'jessica.m@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Q3 Open Enrollment & Benefit Plan Selection Deadline',
    content: 'Hi Alex, please confirm your Q3 health benefit choices in the HR portal before Friday 5:00 PM PST.',
    timestamp: new Date('2026-07-25T13:45:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.MEDIUM,
    tags: ['HR', 'Enrollment', 'Deadline'],
  },
  {
    id: 'msg-109',
    conversationId: 'conv-09',
    platform: PlatformType.GMAIL,
    externalId: 'gm-88231',
    sender: { id: 'usr-fin', name: 'David K. (Finance Lead)', email: 'finance@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Approved: Q3 AI Cloud Infrastructure Budget Stipend ($4,500)',
    content: 'Your expense requisition for GPU cluster expansion ($4,500 USD) has been approved by Finance.',
    timestamp: new Date('2026-07-25T14:15:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.MEDIUM,
    tags: ['Finance', 'Budget', 'Approved'],
  },
  {
    id: 'msg-110',
    conversationId: 'conv-10',
    platform: PlatformType.SLACK,
    externalId: 'slk-33812',
    sender: { id: 'usr-rec', name: 'Rachel Green (Recruitment)', email: 'rachel@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Candidate Interview Feedback Request: Senior AI Systems Engineer',
    content: 'Hey Alex! Could you submit your score and technical notes for today\'s candidate interview (Daniel Vance) in Greenhouse?',
    timestamp: new Date('2026-07-25T14:40:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.MEDIUM,
    tags: ['Recruitment', 'Interview', 'Feedback'],
  },
  {
    id: 'msg-111',
    conversationId: 'conv-11',
    platform: PlatformType.GMAIL,
    externalId: 'gm-66120',
    sender: { id: 'usr-res', name: 'Dr. Aris Thorne (AI Research)', email: 'athorne@mit.edu' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Research Collaboration Paper Draft: Agentic Multi-Tool Reasoning',
    content: 'Alex, I shared the camera-ready LaTeX manuscript for NeurIPS on multi-agent execution graphs. Please review Section 3.4 by tomorrow.',
    timestamp: new Date('2026-07-25T15:05:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.HIGH,
    tags: ['Research', 'NeurIPS', 'Collaboration'],
  },
  {
    id: 'msg-112',
    conversationId: 'conv-12',
    platform: PlatformType.CALENDAR,
    externalId: 'cal-90182',
    sender: { id: 'usr-cal', name: 'Google Calendar Invites', email: 'calendar@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Invitation: Q3 Strategic Architecture Review (Wed 2:00 PM)',
    content: 'You have been invited to Q3 Strategic Architecture Review by Sarah Chen. Agenda: NitroStack multi-agent pipeline roadmap.',
    timestamp: new Date('2026-07-25T15:30:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.HIGH,
    tags: ['Calendar', 'Meeting Invite', 'Architecture'],
  },
  {
    id: 'msg-113',
    conversationId: 'conv-13',
    platform: PlatformType.GITHUB,
    externalId: 'gh-88210',
    sender: { id: 'usr-ghci', name: 'GitHub Actions Bot', avatarUrl: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[CI/CD BUILD FAILURE] Pipeline #1843 Failed on branch dev-mcp',
    content: 'Build failed during step "npm run test:e2e". 2 assertion failures in worker-thread-manager.spec.ts.',
    timestamp: new Date('2026-07-25T16:00:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.URGENT,
    tags: ['GitHub', 'Build Failure', 'CI/CD'],
  },
  {
    id: 'msg-114',
    conversationId: 'conv-14',
    platform: PlatformType.GMAIL,
    externalId: 'gm-44192',
    sender: { id: 'usr-cs', name: 'Enterprise Customer Support Escalation', email: 'support-tier3@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Customer Escalation Ticket #9912: Workspace Sync Delay',
    content: 'Tier 3 Support Escalation: Enterprise client Acme Global reported 4-minute latency on Slack connector sync.',
    timestamp: new Date('2026-07-25T16:20:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.HIGH,
    tags: ['Customer Support', 'Escalation', 'Slack Sync'],
  },
  {
    id: 'msg-115',
    conversationId: 'conv-15',
    platform: PlatformType.SLACK,
    externalId: 'slk-99123',
    sender: { id: 'usr-prod', name: 'Elena Rostova (Product Lead)', email: 'elena@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Feedback Request: Sprint 14 Backlog Grooming',
    content: 'Please check the updated Jira epics for Sprint 14 before tomorrow\'s grooming session.',
    timestamp: new Date('2026-07-25T16:45:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.MEDIUM,
    tags: ['Product', 'Jira', 'Sprint 14'],
  },
  {
    id: 'msg-116',
    conversationId: 'conv-16',
    platform: PlatformType.NOTION,
    externalId: 'ntn-99812',
    sender: { id: 'usr-doc', name: 'Notion Documentation Bot', email: 'docs@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'New Page Added: MCP Server Security Guidelines 2026',
    content: 'Sarah Chen created a new Notion documentation page: "MCP Server Stdio Security Best Practices".',
    timestamp: new Date('2026-07-25T17:10:00Z'),
    status: MessageStatus.UNREAD,
    priority: PriorityLevel.LOW,
    tags: ['Research', 'Notion', 'Security'],
  },

  // --- READ (22 Messages) ---
  {
    id: 'msg-103',
    conversationId: 'conv-03',
    platform: PlatformType.GITHUB,
    externalId: 'gh-44102',
    sender: { id: 'usr-ghbot', name: 'GitHub Actions Bot', avatarUrl: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[CI/CD] Build Succeeded: converra-one/main (Commit 8d3a1f9)',
    content: 'Pipeline #1842 completed successfully in 2m 14s. All 142 unit tests passed.',
    timestamp: new Date('2026-07-25T10:45:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Engineering', 'CI/CD', 'Passing'],
  },
  {
    id: 'msg-105',
    conversationId: 'conv-05',
    platform: PlatformType.NOTION,
    externalId: 'ntn-77412',
    sender: { id: 'usr-pm', name: 'Elena Rostova (Product Lead)', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Q3 Product Roadmap & Agentic AI Milestone Update',
    content: 'Updated Notion database with Q3 deliverables under Section 3: MCP Protocol Integration.',
    timestamp: new Date('2026-07-25T11:55:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Product', 'Roadmap', 'Notion'],
  },
  {
    id: 'msg-117',
    conversationId: 'conv-17',
    platform: PlatformType.GMAIL,
    externalId: 'gm-10029',
    sender: { id: 'usr-aws', name: 'AWS Cloud Notifications', email: 'no-reply@amazon.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'AWS Invoice Summary for June 2026 ($3,120.45)',
    content: 'Your AWS monthly invoice for account 9920-1412 has been processed.',
    timestamp: new Date('2026-07-24T08:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Finance', 'AWS', 'Invoice'],
  },
  {
    id: 'msg-118',
    conversationId: 'conv-18',
    platform: PlatformType.SLACK,
    externalId: 'slk-44912',
    sender: { id: 'usr-dev2', name: 'Liam Patel (Backend Dev)', email: 'liam@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Database Migration Script Completed',
    content: 'Executed PostgreSQL schema migration script v1.4.0 cleanly in staging environment.',
    timestamp: new Date('2026-07-24T09:30:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Engineering', 'Database', 'Migration'],
  },
  {
    id: 'msg-119',
    conversationId: 'conv-19',
    platform: PlatformType.GITHUB,
    externalId: 'gh-99182',
    sender: { id: 'usr-dev3', name: 'Chloe Bennett', email: 'chloe@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Pull Request #341 Merged: Add Stdio MCP Transport Support',
    content: 'PR #341 "Add Stdio MCP Transport Support" approved by Sarah Chen and merged into main.',
    timestamp: new Date('2026-07-24T10:15:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.HIGH,
    tags: ['GitHub', 'PR Review', 'Merged'],
  },
  {
    id: 'msg-120',
    conversationId: 'conv-20',
    platform: PlatformType.GMAIL,
    externalId: 'gm-55192',
    sender: { id: 'usr-zoom', name: 'Zoom Video Communications', email: 'no-reply@zoom.us' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Cloud Recording Ready: Converra All-Hands June Session',
    content: 'The recording for Converra All-Hands June Session is now available for playback.',
    timestamp: new Date('2026-07-24T11:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Calendar', 'Zoom', 'Recording'],
  },
  {
    id: 'msg-121',
    conversationId: 'conv-21',
    platform: PlatformType.SLACK,
    externalId: 'slk-77890',
    sender: { id: 'usr-qa', name: 'Tom Vance (QA Lead)', email: 'tom@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'E2E Automated Test Results: 100% Pass Rate',
    content: 'Automated Playwright regression suite finished with zero failures across Chrome & Firefox.',
    timestamp: new Date('2026-07-24T12:30:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Engineering', 'QA', 'Playwright'],
  },
  {
    id: 'msg-122',
    conversationId: 'conv-22',
    platform: PlatformType.NOTION,
    externalId: 'ntn-11029',
    sender: { id: 'usr-pm2', name: 'Elena Rostova', email: 'elena@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Sprint 13 Retrospective Summary Notes',
    content: 'Added retro action items: 1) Increase multi-agent logging clarity, 2) Optimize build scripts.',
    timestamp: new Date('2026-07-24T13:15:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Sprint', 'Retro'],
  },
  {
    id: 'msg-123',
    conversationId: 'conv-23',
    platform: PlatformType.GMAIL,
    externalId: 'gm-33912',
    sender: { id: 'usr-rec2', name: 'Greenhouse Recruiting', email: 'no-reply@greenhouse.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Interview Scheduled: Technical Architecture Interview with Candidate A',
    content: 'Interview confirmed for Thursday at 11:00 AM PST. Google Meet link generated.',
    timestamp: new Date('2026-07-24T14:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Recruitment', 'Interview', 'Greenhouse'],
  },
  {
    id: 'msg-124',
    conversationId: 'conv-24',
    platform: PlatformType.DISCORD,
    externalId: 'dsc-55102',
    sender: { id: 'usr-dev4', name: 'Kevin Durant (DevOps)', email: 'kevin@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Kubernetes Ingress Controller Certificate Renewal',
    content: 'TLS Let\'s Encrypt certificates automatically renewed for *.converra.io domain endpoints.',
    timestamp: new Date('2026-07-24T14:45:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'DevOps', 'SSL'],
  },
  {
    id: 'msg-125',
    conversationId: 'conv-25',
    platform: PlatformType.SLACK,
    externalId: 'slk-00192',
    sender: { id: 'usr-sec2', name: 'Security Bot', email: 'secbot@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Weekly Security Audit: Zero Active Vulnerabilities',
    content: 'Snyk and Dependabot static code scanners completed weekly audit with clean report.',
    timestamp: new Date('2026-07-24T15:20:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'Security', 'Snyk'],
  },
  {
    id: 'msg-126',
    conversationId: 'conv-26',
    platform: PlatformType.GMAIL,
    externalId: 'gm-77491',
    sender: { id: 'usr-hr2', name: 'Converra HR Portal', email: 'hr@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Company Holiday Schedule Announcement: Labor Day Office Closure',
    content: 'Converra offices will be closed on Monday September 7 in observance of Labor Day.',
    timestamp: new Date('2026-07-24T16:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['HR', 'Holiday', 'Announcement'],
  },
  {
    id: 'msg-127',
    conversationId: 'conv-27',
    platform: PlatformType.GITHUB,
    externalId: 'gh-33102',
    sender: { id: 'usr-ghrev', name: 'Sarah Chen', email: 'sarah.chen@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Approved PR #340: Refactor Priority Agent Scoring Matrix',
    content: 'Sarah Chen approved pull request #340 with comment: "Looks clean, great work Alex!"',
    timestamp: new Date('2026-07-23T09:15:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['GitHub', 'PR Approved', 'Priority Agent'],
  },
  {
    id: 'msg-128',
    conversationId: 'conv-28',
    platform: PlatformType.SLACK,
    externalId: 'slk-99120',
    sender: { id: 'usr-mktg', name: 'Sophia Martinez (Marketing)', email: 'sophia@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Press Release Draft: Converra One AI Studio Launch',
    content: 'Shared draft press release for product launch on TechCrunch. Need engineering quote by Friday.',
    timestamp: new Date('2026-07-23T10:30:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Product', 'Marketing', 'Press Release'],
  },
  {
    id: 'msg-129',
    conversationId: 'conv-29',
    platform: PlatformType.GMAIL,
    externalId: 'gm-88129',
    sender: { id: 'usr-fin2', name: 'Expensify Receipts', email: 'receipts@expensify.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Expense Report Submitted: Team Lunch ($142.80)',
    content: 'Your expense report for team lunch has been submitted for manager approval.',
    timestamp: new Date('2026-07-23T11:45:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Finance', 'Expensify', 'Receipt'],
  },
  {
    id: 'msg-130',
    conversationId: 'conv-30',
    platform: PlatformType.CALENDAR,
    externalId: 'cal-88912',
    sender: { id: 'usr-cal2', name: 'Google Calendar Invites', email: 'calendar@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Accepted: 1:1 Bi-weekly Sync with Elena Rostova',
    content: 'Elena Rostova accepted your event invitation for Thursday 4:00 PM.',
    timestamp: new Date('2026-07-23T13:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Calendar', '1:1', 'Accepted'],
  },
  {
    id: 'msg-131',
    conversationId: 'conv-31',
    platform: PlatformType.NOTION,
    externalId: 'ntn-44812',
    sender: { id: 'usr-pm3', name: 'Elena Rostova', email: 'elena@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Updated Page: NitroStack Agentic AI Architecture Diagram',
    content: 'Added Mermaid flowcharts for OrchestratorAgent, CalendarAgent, and ReplyAgent.',
    timestamp: new Date('2026-07-23T14:30:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.MEDIUM,
    tags: ['Research', 'Notion', 'Architecture'],
  },
  {
    id: 'msg-132',
    conversationId: 'conv-32',
    platform: PlatformType.SLACK,
    externalId: 'slk-22910',
    sender: { id: 'usr-dev5', name: 'Marcus Brody', email: 'marcus@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Tailwind Glassmorphism CSS Utility Class Guidelines',
    content: 'Posted CSS utility rules for backdrop-blur-md and custom border glowing shadows in #frontend-dev.',
    timestamp: new Date('2026-07-23T15:40:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Frontend', 'CSS'],
  },
  {
    id: 'msg-133',
    conversationId: 'conv-33',
    platform: PlatformType.GMAIL,
    externalId: 'gm-99281',
    sender: { id: 'usr-stan', name: 'Stanford CS Alumni Network', email: 'alumni@cs.stanford.edu' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Monthly CS Research Symposium Newsletter - July 2026 Edition',
    content: 'Highlights: Distributed consensus systems, Agentic AI reasoning, and LLM quantization techniques.',
    timestamp: new Date('2026-07-23T16:50:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Research', 'Stanford', 'Newsletter'],
  },
  {
    id: 'msg-134',
    conversationId: 'conv-34',
    platform: PlatformType.GITHUB,
    externalId: 'gh-11029',
    sender: { id: 'usr-ghst', name: 'GitHub Dependabot', avatarUrl: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Bump typescript from 5.4.2 to 5.5.3 in /package.json',
    content: 'Dependabot created PR #339 to update TypeScript compiler dependencies.',
    timestamp: new Date('2026-07-22T09:00:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['GitHub', 'Dependabot', 'TypeScript'],
  },
  {
    id: 'msg-135',
    conversationId: 'conv-35',
    platform: PlatformType.SLACK,
    externalId: 'slk-88120',
    sender: { id: 'usr-ops', name: 'OpsGenie Incident Bot', email: 'alerts@opsgenie.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[RESOLVED] Alert #4491: High CPU Utilization on Redis Primary',
    content: 'Alert #4491 auto-resolved. Redis cache cluster CPU returned to baseline 14%.',
    timestamp: new Date('2026-07-22T11:20:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'OpsGenie', 'Resolved'],
  },
  {
    id: 'msg-136',
    conversationId: 'conv-36',
    platform: PlatformType.GMAIL,
    externalId: 'gm-33019',
    sender: { id: 'usr-uber', name: 'Uber Receipts', email: 'uber.receipts@uber.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: 'Your Ride with Uber on Wednesday Evening ($24.50)',
    content: 'Trip receipt from Converra HQ to Stanford Campus. Charged to Visa ending in 4920.',
    timestamp: new Date('2026-07-22T19:30:00Z'),
    status: MessageStatus.READ,
    priority: PriorityLevel.LOW,
    tags: ['Finance', 'Uber', 'Receipt'],
  },

  // --- ARCHIVED (10 Messages) ---
  {
    id: 'msg-137',
    conversationId: 'conv-37',
    platform: PlatformType.GMAIL,
    externalId: 'gm-00129',
    sender: { id: 'usr-old1', name: 'Q2 Sprint Planning Board', email: 'planning@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Q2 Sprint 10 Goal Confirmation',
    content: 'Sprint 10 goals confirmed. Archived for historical audit record.',
    timestamp: new Date('2026-06-15T09:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Archived', 'Q2 Goals'],
  },
  {
    id: 'msg-138',
    conversationId: 'conv-38',
    platform: PlatformType.SLACK,
    externalId: 'slk-00182',
    sender: { id: 'usr-old2', name: 'DevOps Maintenance Bot', email: 'devops@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Scheduled Staging DB Maintenance Complete',
    content: 'Staging environment database upgrade completed successfully.',
    timestamp: new Date('2026-06-18T10:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'Archived', 'Maintenance'],
  },
  {
    id: 'msg-139',
    conversationId: 'conv-39',
    platform: PlatformType.GMAIL,
    externalId: 'gm-00281',
    sender: { id: 'usr-old3', name: 'Stripe Payments', email: 'support@stripe.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Stripe Developer Account Verification Completed',
    content: 'Developer API keys successfully generated for live payment webhooks.',
    timestamp: new Date('2026-06-20T11:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Finance', 'Stripe', 'Archived'],
  },
  {
    id: 'msg-140',
    conversationId: 'conv-40',
    platform: PlatformType.GITHUB,
    externalId: 'gh-00912',
    sender: { id: 'usr-old4', name: 'GitHub Releases', email: 'no-reply@github.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Release v1.2.0 Tagged on converra-one',
    content: 'Tag v1.2.0 successfully published to Docker Hub registry.',
    timestamp: new Date('2026-06-22T14:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['GitHub', 'Release', 'Archived'],
  },
  {
    id: 'msg-141',
    conversationId: 'conv-41',
    platform: PlatformType.NOTION,
    externalId: 'ntn-00129',
    sender: { id: 'usr-old5', name: 'Elena Rostova', email: 'elena@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Old Q1 Architecture Brainstorm Document',
    content: 'Archived initial design proposal for legacy REST connector layer.',
    timestamp: new Date('2026-06-25T15:30:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Notion', 'Archived'],
  },
  {
    id: 'msg-142',
    conversationId: 'conv-42',
    platform: PlatformType.GMAIL,
    externalId: 'gm-00481',
    sender: { id: 'usr-old6', name: 'Jessica Miller', email: 'jessica.m@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Q2 Performance Review Completion Sign-off',
    content: 'Q2 Performance review cycle completed. Submitted to HR database.',
    timestamp: new Date('2026-06-28T16:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['HR', 'Review', 'Archived'],
  },
  {
    id: 'msg-143',
    conversationId: 'conv-43',
    platform: PlatformType.SLACK,
    externalId: 'slk-00591',
    sender: { id: 'usr-old7', name: 'Sarah Chen', email: 'sarah.chen@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Legacy Webhook Deprecation Notice',
    content: 'All legacy webhooks migrated to MCP stdio endpoints.',
    timestamp: new Date('2026-07-01T09:30:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'Slack', 'Archived'],
  },
  {
    id: 'msg-144',
    conversationId: 'conv-44',
    platform: PlatformType.DISCORD,
    externalId: 'dsc-00120',
    sender: { id: 'usr-old8', name: 'Marcus Brody', email: 'marcus@converra.io' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Old Color Palette Guidelines (v1.0)',
    content: 'Superseded by v2.0 Glassmorphism Dark System.',
    timestamp: new Date('2026-07-05T11:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Product', 'Design', 'Archived'],
  },
  {
    id: 'msg-145',
    conversationId: 'conv-45',
    platform: PlatformType.GMAIL,
    externalId: 'gm-00612',
    sender: { id: 'usr-old9', name: 'Google Cloud Platform', email: 'cloud-billing@google.com' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] GCP Free Trial Credit Expiration Notice',
    content: 'GCP Trial credits fully transitioned to corporate invoice billing account.',
    timestamp: new Date('2026-07-10T14:15:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Finance', 'GCP', 'Archived'],
  },
  {
    id: 'msg-146',
    conversationId: 'conv-46',
    platform: PlatformType.GITHUB,
    externalId: 'gh-00781',
    sender: { id: 'usr-old10', name: 'GitHub Actions Bot', avatarUrl: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png' },
    recipients: [{ id: 'usr-me', name: 'Alex Mercer', email: 'alex.mercer@converra.io' }],
    subject: '[ARCHIVED] Docker Layer Cache Cleanup Task Completed',
    content: 'Pruned 14GB of unused container image layers from CI runner storage.',
    timestamp: new Date('2026-07-15T17:00:00Z'),
    status: MessageStatus.ARCHIVED,
    priority: PriorityLevel.LOW,
    tags: ['Engineering', 'Docker', 'Archived'],
  }
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-01',
    title: 'Adjust Raft Consensus Timeout Parameters for Prof. Vance',
    description: 'Review section 4.2 of CS340 blueprint and submit updated config params prior to review call.',
    status: TaskStatus.PENDING,
    priority: PriorityLevel.URGENT,
    sourcePlatform: PlatformType.GMAIL,
    sourceMessageId: 'msg-101',
    assignee: 'Alex Mercer',
    dueDate: new Date('2026-07-25T15:00:00Z'),
    createdAt: new Date('2026-07-25T09:16:00Z'),
    updatedAt: new Date('2026-07-25T09:16:00Z'),
    tags: ['Academic', 'Raft', 'Urgent'],
  },
  {
    id: 'task-02',
    title: 'Investigate NitroStack Worker Node 3 Memory Leak (PR #342)',
    description: 'Analyze heap snapshot from stress test on worker node 3 with Sarah Chen.',
    status: TaskStatus.IN_PROGRESS,
    priority: PriorityLevel.HIGH,
    sourcePlatform: PlatformType.SLACK,
    sourceMessageId: 'msg-102',
    assignee: 'Alex Mercer',
    dueDate: new Date('2026-07-25T17:30:00Z'),
    createdAt: new Date('2026-07-25T10:05:00Z'),
    updatedAt: new Date('2026-07-25T10:05:00Z'),
    tags: ['Backend', 'Memory', 'PR #342'],
  },
  {
    id: 'task-03',
    title: 'Update Notion Deliverables for Q3 MCP Integration Roadmap',
    description: 'Fill in estimated completion dates for agentic workflow milestones.',
    status: TaskStatus.PENDING,
    priority: PriorityLevel.MEDIUM,
    sourcePlatform: PlatformType.NOTION,
    sourceMessageId: 'msg-105',
    assignee: 'Alex Mercer',
    dueDate: new Date('2026-07-26T12:00:00Z'),
    createdAt: new Date('2026-07-25T11:56:00Z'),
    updatedAt: new Date('2026-07-25T11:56:00Z'),
    tags: ['Product', 'Roadmap'],
  },
  {
    id: 'task-04',
    title: 'Review Marcus Figma Design Tokens for Glassmorphism Cards',
    description: 'Validate color variables in theme.config.ts against Figma specifications.',
    status: TaskStatus.COMPLETED,
    priority: PriorityLevel.LOW,
    sourcePlatform: PlatformType.DISCORD,
    sourceMessageId: 'msg-104',
    assignee: 'Alex Mercer',
    dueDate: new Date('2026-07-24T18:00:00Z'),
    createdAt: new Date('2026-07-24T11:20:00Z'),
    updatedAt: new Date('2026-07-25T08:00:00Z'),
    tags: ['UI/UX', 'Done'],
  }
];

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-01',
    title: 'Prof. Vance CS340 Project Architecture Call',
    description: '15-min sync to review Raft consensus parameters and blueprint updates.',
    startTime: new Date('2026-07-25T15:00:00Z'),
    endTime: new Date('2026-07-25T15:15:00Z'),
    isAllDay: false,
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    organizer: { name: 'Dr. Evelyn Vance', email: 'e.vance@stanford.edu', responseStatus: 'accepted' },
    attendees: [
      { name: 'Dr. Evelyn Vance', email: 'e.vance@stanford.edu', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-02',
    title: 'NitroStack Engineering Daily Standup & PR Sync',
    description: 'Daily team standup discussing release candidate blockers and agentic AI tools.',
    startTime: new Date('2026-07-25T16:30:00Z'),
    endTime: new Date('2026-07-25T17:00:00Z'),
    isAllDay: false,
    location: 'Slack Huddle (#engineering-core)',
    meetingUrl: 'https://slack.com/huddle/converra-eng',
    organizer: { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
      { name: 'Marcus Brody', email: 'marcus.brody@converra.io', responseStatus: 'tentative' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-03',
    title: 'Hackathon Demo Prep & Presentation Dry Run',
    description: 'Reviewing NitroStack Studio widgets, multi-agent timelines, and MCP tool triggers.',
    startTime: new Date('2026-07-25T19:00:00Z'),
    endTime: new Date('2026-07-25T20:00:00Z'),
    isAllDay: false,
    location: 'Zoom Main Room',
    meetingUrl: 'https://zoom.us/j/991204812',
    organizer: { name: 'Elena Rostova', email: 'elena@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Elena Rostova', email: 'elena@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-04',
    title: 'Client Enterprise Architecture Review (Acme Global)',
    description: 'Technical deep-dive into multi-agent connector security & zero-trust MCP pipes.',
    startTime: new Date('2026-07-26T10:00:00Z'),
    endTime: new Date('2026-07-26T11:00:00Z'),
    isAllDay: false,
    location: 'Google Meet (Client Room)',
    meetingUrl: 'https://meet.google.com/acme-arch-rev',
    organizer: { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
      { name: 'Acme CTO', email: 'cto@acmeglobal.com', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-05',
    title: 'Deep Focus Block: Memory Leak Resolution (PR #342)',
    description: 'Undisturbed coding block for GC tuning and worker node 3 profiling.',
    startTime: new Date('2026-07-26T11:30:00Z'),
    endTime: new Date('2026-07-26T13:00:00Z'),
    isAllDay: false,
    location: 'Focus Room 4B / Offline',
    organizer: { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
    attendees: [{ name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-06',
    title: 'Engineering Team Catering & Social Lunch Block',
    description: 'Weekly informal team lunch and coffee break at HQ cafeteria.',
    startTime: new Date('2026-07-26T13:00:00Z'),
    endTime: new Date('2026-07-26T14:00:00Z'),
    isAllDay: false,
    location: 'Converra HQ Cafeteria',
    organizer: { name: 'Jessica Miller', email: 'jessica.m@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
      { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-07',
    title: 'Design System & Glassmorphism Review Workshop',
    description: 'Collaborating with Marcus Brody on Figma token export and theme switches.',
    startTime: new Date('2026-07-26T14:30:00Z'),
    endTime: new Date('2026-07-26T15:30:00Z'),
    isAllDay: false,
    location: 'Design Studio Lab',
    meetingUrl: 'https://zoom.us/j/109283481',
    organizer: { name: 'Marcus Brody', email: 'marcus@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Marcus Brody', email: 'marcus@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-08',
    title: 'Candidate Technical Interview (Sr. AI Systems Engineer)',
    description: 'Conducting live coding assessment and system design interview.',
    startTime: new Date('2026-07-26T16:00:00Z'),
    endTime: new Date('2026-07-26T17:00:00Z'),
    isAllDay: false,
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/interview-room-1',
    organizer: { name: 'Rachel Green', email: 'rachel@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
      { name: 'Daniel Vance (Candidate)', email: 'daniel.v@gmail.com', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-09',
    title: '1:1 Bi-Weekly Sync with Elena Rostova (Product Lead)',
    description: 'Reviewing Q3 roadmap deliverables, OKRs, and upcoming release timelines.',
    startTime: new Date('2026-07-27T10:00:00Z'),
    endTime: new Date('2026-07-27T10:30:00Z'),
    isAllDay: false,
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/elena-alex-sync',
    organizer: { name: 'Elena Rostova', email: 'elena@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Elena Rostova', email: 'elena@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-10',
    title: 'NeurIPS Paper Draft Review with MIT AI Lab',
    description: 'Reviewing Section 3.4 on agentic execution graphs with Dr. Aris Thorne.',
    startTime: new Date('2026-07-27T11:00:00Z'),
    endTime: new Date('2026-07-27T12:00:00Z'),
    isAllDay: false,
    location: 'Zoom (MIT Research)',
    meetingUrl: 'https://mit.zoom.us/j/88210291',
    organizer: { name: 'Dr. Aris Thorne', email: 'athorne@mit.edu', responseStatus: 'accepted' },
    attendees: [
      { name: 'Dr. Aris Thorne', email: 'athorne@mit.edu', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-11',
    title: 'Personal Dentist Reminder',
    description: 'Annual routine dental checkup & cleaning.',
    startTime: new Date('2026-07-27T13:30:00Z'),
    endTime: new Date('2026-07-27T14:15:00Z'),
    isAllDay: false,
    location: 'Palo Alto Dental Center',
    organizer: { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
    attendees: [{ name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-12',
    title: 'Code Review Block: Pull Requests #343 - #346',
    description: 'Dedicated code review time for incoming team PRs on GitHub.',
    startTime: new Date('2026-07-27T15:00:00Z'),
    endTime: new Date('2026-07-27T16:30:00Z'),
    isAllDay: false,
    location: 'GitHub / Workspace',
    organizer: { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
    attendees: [{ name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-13',
    title: 'Converra Global All-Hands Company Meeting',
    description: 'Monthly company-wide updates, revenue goals, and product demos.',
    startTime: new Date('2026-07-28T09:00:00Z'),
    endTime: new Date('2026-07-28T10:00:00Z'),
    isAllDay: false,
    location: 'Zoom Auditorium',
    meetingUrl: 'https://zoom.us/j/all-hands-converra',
    organizer: { name: 'Jessica Miller', email: 'jessica.m@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' },
      { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-14',
    title: 'Project Deadline: NitroStack v1.4 Final RC Freeze',
    description: 'Official code freeze deadline for v1.4 release candidate build.',
    startTime: new Date('2026-07-28T17:00:00Z'),
    endTime: new Date('2026-07-28T18:00:00Z'),
    isAllDay: false,
    location: 'GitHub Release Tag',
    organizer: { name: 'Sarah Chen', email: 'sarah.chen@converra.io', responseStatus: 'accepted' },
    attendees: [{ name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-15',
    title: 'Travel Flight Reminder: SFO → JFK (AI Summit Conference)',
    description: 'Flight UA2401 to New York JFK for AI Summit 2026 Keynote.',
    startTime: new Date('2026-07-29T08:00:00Z'),
    endTime: new Date('2026-07-29T14:30:00Z'),
    isAllDay: false,
    location: 'San Francisco International Airport (SFO)',
    organizer: { name: 'United Airlines', email: 'travel@united.com', responseStatus: 'accepted' },
    attendees: [{ name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }],
    platform: PlatformType.CALENDAR
  },
  {
    id: 'evt-16',
    title: 'Meeting Conflict: Urgent Incident Response Retrospective',
    description: 'Reviewing Redis cache CPU alert #4491 root cause analysis.',
    startTime: new Date('2026-07-29T11:00:00Z'),
    endTime: new Date('2026-07-29T11:45:00Z'),
    isAllDay: false,
    location: 'Slack Huddle (War Room)',
    meetingUrl: 'https://slack.com/huddle/warroom',
    organizer: { name: 'Kevin Durant', email: 'kevin@converra.io', responseStatus: 'accepted' },
    attendees: [
      { name: 'Kevin Durant', email: 'kevin@converra.io', responseStatus: 'accepted' },
      { name: 'Alex Mercer', email: 'alex.mercer@converra.io', responseStatus: 'accepted' }
    ],
    platform: PlatformType.CALENDAR
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-01',
    type: NotificationType.MESSAGE_URGENT,
    title: 'Urgent Email from Prof. Evelyn Vance',
    body: 'CS340 Raft consensus blueprint requires immediate timeout adjustment prior to 3 PM call.',
    priority: PriorityLevel.URGENT,
    isRead: false,
    createdAt: new Date('2026-07-25T09:16:00Z'),
    metadata: { sourcePlatform: 'GMAIL', messageId: 'msg-101' }
  },
  {
    id: 'notif-02',
    type: NotificationType.TASK_DUE,
    title: 'Task Due in 2 Hours',
    body: 'Investigate NitroStack Worker Node 3 Memory Leak (PR #342)',
    priority: PriorityLevel.HIGH,
    isRead: false,
    createdAt: new Date('2026-07-25T10:05:00Z'),
    metadata: { taskId: 'task-02' }
  },
  {
    id: 'notif-03',
    type: NotificationType.AI_SUMMARY_READY,
    title: 'Daily AI Briefing Synthesized',
    body: 'Priority Agent scored 2 urgent threads. 1 calendar conflict auto-resolved.',
    priority: PriorityLevel.MEDIUM,
    isRead: true,
    createdAt: new Date('2026-07-25T08:00:00Z')
  }
];

export const MOCK_AGENT_LOGS: AgentExecutionLog[] = [
  {
    id: 'log-01',
    agent: AgentType.COLLECTOR,
    agentName: 'Collector Agent',
    action: 'Harvested Channel Stream',
    details: 'Ingested 14 Gmail threads, 28 Slack messages, 8 Discord alerts across 6 integrations',
    timestamp: '10:02:14 AM',
    durationMs: 84,
    status: 'completed',
    mcpTool: 'mcp_harvest_channels'
  },
  {
    id: 'log-02',
    agent: AgentType.PRIORITY,
    agentName: 'Priority Agent',
    action: 'Urgency Classification',
    details: 'Flagged msg-101 (Prof. Vance) as URGENT (Score: 0.96) based on deadline and sender authority',
    timestamp: '10:02:15 AM',
    durationMs: 120,
    status: 'completed',
    mcpTool: 'mcp_score_urgency'
  },
  {
    id: 'log-03',
    agent: AgentType.SUMMARY,
    agentName: 'Summary Agent',
    action: 'Thread Summarization',
    details: 'Generated 3-bullet executive briefing for PR #342 and CS340 Architecture Blueprint',
    timestamp: '10:02:16 AM',
    durationMs: 210,
    status: 'completed',
    mcpTool: 'mcp_summarize_thread'
  },
  {
    id: 'log-04',
    agent: AgentType.TASK,
    agentName: 'Task Agent',
    action: 'Action Item Extraction',
    details: 'Extracted task: "Adjust Raft Timeout Parameters" with due date 2026-07-25T15:00:00Z',
    timestamp: '10:02:17 AM',
    durationMs: 95,
    status: 'completed',
    mcpTool: 'mcp_extract_tasks'
  },
  {
    id: 'log-05',
    agent: AgentType.CALENDAR,
    agentName: 'Calendar Agent',
    action: 'Schedule Verification',
    details: 'Verified 3:00 PM slot availability for Prof. Vance call with zero calendar conflicts',
    timestamp: '10:02:18 AM',
    durationMs: 65,
    status: 'completed',
    mcpTool: 'mcp_check_calendar'
  },
  {
    id: 'log-06',
    agent: AgentType.REPLY,
    agentName: 'Reply Agent',
    action: 'Smart Draft Preparation',
    details: 'Prepared Professional tone response accepting 3:00 PM call and confirming parameter review',
    timestamp: '10:02:19 AM',
    durationMs: 145,
    status: 'completed',
    mcpTool: 'mcp_generate_reply'
  }
];

export const MOCK_SEARCH_QUERY_RESPONSE = {
  query: "What did my professor say about the project?",
  answer: "Dr. Evelyn Vance sent an urgent email regarding your CS340 Final Project Architecture Blueprint. She requested that you adjust the Raft consensus layer timeout parameters in section 4.2 before a 15-minute review call scheduled for today at 3:00 PM.",
  sources: [
    {
      id: 'msg-101',
      platform: PlatformType.GMAIL,
      sender: 'Dr. Evelyn Vance (e.vance@stanford.edu)',
      subject: 'URGENT: Review CS340 Final Project Architecture Blueprint',
      snippet: '...we need to adjust the raft consensus layer timeout parameters before Monday morning review...',
      relevanceScore: 0.98,
      timestamp: '9:15 AM Today'
    }
  ],
  relatedMessages: [
    {
      id: 'msg-105',
      platform: PlatformType.NOTION,
      sender: 'Elena Rostova',
      subject: 'Q3 Product Roadmap & Agentic AI Milestone Update',
      snippet: 'Updated Notion database with Q3 deliverables...',
      relevanceScore: 0.72
    }
  ]
};
