from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from threading import RLock
from typing import Any, Callable, DefaultDict, Dict, List
from collections import defaultdict
from uuid import uuid4


@dataclass
class AgentEvent:
    """
    Represents a single event generated by an agent.
    """

    event_id: str = field(default_factory=lambda: str(uuid4()))

    event_type: str = ""

    source: str = ""

    payload: Dict[str, Any] = field(default_factory=dict)

    timestamp: str = field(
        default_factory=lambda: datetime.utcnow().isoformat()
    )


class AgentEventBus:
    """
    Enterprise Event Bus.

    Responsibilities

        • Publish events
        • Subscribe to events
        • Unsubscribe handlers
        • Maintain event history
        • Dispatch listeners
    """

    def __init__(self):

        self._subscribers: DefaultDict[
            str,
            List[Callable[[AgentEvent], None]]
        ] = defaultdict(list)

        self._history: List[AgentEvent] = []

        self._lock = RLock()

    # --------------------------------------------------
    # Subscription
    # --------------------------------------------------

    def subscribe(
        self,
        event_type: str,
        handler: Callable[[AgentEvent], None],
    ) -> None:

        with self._lock:

            if handler not in self._subscribers[event_type]:
                self._subscribers[event_type].append(handler)

    def unsubscribe(
        self,
        event_type: str,
        handler: Callable[[AgentEvent], None],
    ) -> None:

        with self._lock:

            if (
                event_type in self._subscribers
                and handler in self._subscribers[event_type]
            ):

                self._subscribers[event_type].remove(handler)

    # --------------------------------------------------
    # Publishing
    # --------------------------------------------------

    def publish(
        self,
        event_type: str,
        source: str,
        payload: Dict[str, Any] | None = None,
    ) -> AgentEvent:

        event = AgentEvent(
            event_type=event_type,
            source=source,
            payload=payload or {},
        )

        self._history.append(event)

        handlers = list(
            self._subscribers.get(event_type, [])
        )

        for handler in handlers:

            try:

                handler(event)

            except Exception:

                # Future versions can integrate
                # enterprise logging here.
                pass

        return event

    # --------------------------------------------------
    # Retrieval
    # --------------------------------------------------

    def history(self) -> List[AgentEvent]:

        return list(self._history)

    def events(
        self,
        event_type: str,
    ) -> List[AgentEvent]:

        return [
            event
            for event in self._history
            if event.event_type == event_type
        ]

    # --------------------------------------------------
    # Statistics
    # --------------------------------------------------

    def statistics(self) -> Dict[str, Any]:

        counts = {}

        for event in self._history:

            counts.setdefault(
                event.event_type,
                0,
            )

            counts[event.event_type] += 1

        return {
            "events": len(self._history),
            "subscribers": {
                event: len(handlers)
                for event, handlers
                in self._subscribers.items()
            },
            "event_counts": counts,
        }

    # --------------------------------------------------
    # Diagnostics
    # --------------------------------------------------

    def diagnostics(self) -> Dict[str, Any]:

        return {
            "statistics": self.statistics(),
            "registered_events": sorted(
                self._subscribers.keys()
            ),
        }

    # --------------------------------------------------
    # Maintenance
    # --------------------------------------------------

    def clear(self) -> None:

        self._history.clear()

    # --------------------------------------------------
    # Serialization
    # --------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:

        return {
            "history": [
                {
                    "event_id": event.event_id,
                    "event_type": event.event_type,
                    "source": event.source,
                    "payload": event.payload,
                    "timestamp": event.timestamp,
                }
                for event in self._history
            ]
        }

    # --------------------------------------------------
    # Magic Methods
    # --------------------------------------------------

    def __len__(self):

        return len(self._history)

    def __repr__(self):

        return (
            f"AgentEventBus("
            f"events={len(self)}, "
            f"types={len(self._subscribers)})"
        )